### ISSUE TITLE
Call4Makers OSHWDEM - Grupo Printer One

### ISSUE THREAD

**Issue by d-marcos-m** [asrob-uc3m/impresoras-asrob#100]
Holi,

Sigue abierto el Call4Makers de la oshwdem, propongo intentar llevar algo del grupo. Opiniones? Propuestas? Insultos?

**Comment by d-marcos-m** [comment]
Parece que ya está pedido a nombre de Asrob. Porfa @JorFru coméntalo en una issue en actas.

**Comment by David-Estevez** [comment]
Hecho: https://github.com/asrob-uc3m/actas/issues/169  (yo también estaba en el ajo)
