### ISSUE TITLE
Comprar nuevos filamentos

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#102]
Para apurar el presupuesto de las subvenciones, @GioSunrider y yo hemos pensado en pedir bobinas de filamento. Se aceptan sugerencias.

**Comment by JorFru** [comment]
Yo quiero esto papi

https://www.materials3dimpresion.com/pla_ep.php?l=0
Xoán maestroimprusador recomienda BLANCO GLACIAR del producto PLA EP (Easy Print)

**Comment by d-marcos-m** [comment]
- https://fillamentum.com/products/pla-extrafill-vertigo-grey o https://fervi3d.com/fiberlogy-easy-pla/335-722-fiberlogy-easy-pla-vertigo.html
- https://smartmaterials3d.com/es/tienda-smart/20-smartfil-flex.html#/diametro-1_75_mm_0_03/color-ruby/tamano-s_330g
- https://smartmaterials3d.com/es/smartfil-pla/72-smartfil-pla-mix.html 
No se cuanto dinero hay pero quizá nos interesa probar el Nylon: https://fervi3d.com/fiberlogy-nylon-pa12/448-903-nylon-pa12-black.html#/25-diametro-175_mm/28-tamano-m_750_g

**Comment by GioSunrider** [comment]
Para variar un poco de filamentos yo propongo PETG de Fiberlogy que tiene muy buena calidad. https://www.3dpenedes.com/es/filamento/973-pet-g-azul-transparente.html

**Comment by d-marcos-m** [comment]
Cuánto hay sobrante @Siotma?

**Comment by GioSunrider** [comment]
No era mucho, unos 60 creo recordar, pero lo de los filamentos lo dejaremos para la ultima semana de octubre no vaya a ser que necesitemos algo antes y no podamos.

**Comment by d-marcos-m** [comment]
Vale, perfecto. 
Entonces si nos quedan esos 60 en el momento que los compremos, la lista podría ser esta: (un poco de todo)

- PETG Fiberlogy Azul Transparente: https://fervi3d.com/fiberlogy-petg/330-717-fiberlogy-petg-tr-navy-blue.html#/25-diametro-175_mm/98-tamano-xm_850_g (más barato aquí)
- PLA Vertigo Fiberlogy: https://fervi3d.com/fiberlogy-easy-pla/335-722-fiberlogy-easy-pla-vertigo.html
- Smartfil PLA Fluorescente: https://fervi3d.com/smartfil-pla/17-101-pla-smart-glow.html#/25-diametro-175_mm/27-tamano-s_330_g
- Smartfil Flex <color>: https://fervi3d.com/smartfil-flex/13-89-flex.html#/25-diametro-175_mm/27-tamano-s_330_g/34-color-sapphire

**Comment by Siotma** [comment]
Tienen todos muy buena pinta.

Una vez veamos el dinero disponible, realizaré la compra :wink:

**Comment by Siotma** [comment]
Esta cesta de la compra liquidaría las subvenciones:

![imagen](https://user-images.githubusercontent.com/6171234/47234601-a1740f00-d3d6-11e8-9082-1bd9e8c10c55.png)

**Comment by d-marcos-m** [comment]
> Esta cesta de la compra liquidaría las subvenciones:
> 
> ![imagen](https://user-images.githubusercontent.com/6171234/47234601-a1740f00-d3d6-11e8-9082-1bd9e8c10c55.png)

A mi me parece correcto :)

**Comment by GioSunrider** [comment]
Se que no viene a cuento pero... y algo de estaño? en general estamos muy necesitados de el, se podria incluir?

**Comment by d-marcos-m** [comment]
La cosa es que el filamento es algo que hay qee comprar vía la issue de material común, no? De hecho creo que ya está puesto allí.

**Comment by GioSunrider** [comment]
Me refería para terminar de cuadrar las cuentas.

**Comment by d-marcos-m** [comment]
Pero habría que quitar algún filamento entonces, porque con lo poco que "sobra" no compras demasiado estaño xD 
(si hay que quitar alguno yo pasaría del Smart Glow)

**Comment by GioSunrider** [comment]
Yo quitaría el smart glow, además para así comprar kits para el ajuste del extrusor para las otras impresoras.

**Comment by JorFru** [comment]
Del estaño me encargo yo. Dedicad el presupuesto de Printer para filamentos y componentes.

**Comment by Siotma** [comment]
Hoy se han comprado 4 filamentos:
- https://fervi3d.com/smartfil-flex-93a/13-89-flex.html#/25-diametro-175_mm/27-tamano-s_330_g/34-color-sapphire
- https://fervi3d.com/fiberlogy-petg/330-717-fiberlogy-petg-tr-navy-blue.html#/25-diametro-175_mm/98-tamano-xm_850_g
- https://fervi3d.com/esencial-pla/406-790-pla-fervi3d-esencial.html#/25-diametro-175_mm/28-tamano-m_750_g/105-color_esencial-verde_luminoso
- https://fervi3d.com/fiberlogy-easy-pla/444-895-fiberlogy-easy-pla-onix.html#/25-diametro-175_mm/98-tamano-xm_850_g

**Comment by Siotma** [comment]
Los filamentos llegaron hace unos días. Los llevaré en la próxima reunión:

![17_nov_new_filaments_and_parts](https://user-images.githubusercontent.com/6171234/48676645-d4dac280-eb69-11e8-8050-7923e84951f2.jpg)
