### ISSUE TITLE
Comprar muelles para las camas calientes

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#103]
Desgraciadamente, algunas impresoras, como Hija Resurrection, tienen muelles lamentables en la cama caliente, que dificultan su calibración y mantenimiento. Propongo comprar nuevos muelles para todas las impresoras que los necesiten: https://fervi3d.com/mecanica/188-muelles-cama-calienta-pack-4unidades.html

**Comment by GioSunrider** [comment]
Me parece una idea genial y un gasto mas que justificado, dado que a las impresoras les baila mucho la cama.

**Comment by d-marcos-m** [comment]
Dale, compra 3 kits y listo!

**Comment by d-marcos-m** [comment]
Muelles, tambien en Fervi3d: https://fervi3d.com/mecanica/188-muelles-cama-calienta-pack-4unidades.html 

1,50€ por cada 4 unidades :+1:

**Comment by Siotma** [comment]
Hoy se han comprado 3 kits de 4 muelles en https://fervi3d.com/mecanica/188-muelles-cama-calienta-pack-4unidades.html

**Comment by Siotma** [comment]
Los muelles llegaron hace unos días. Los llevaré en la próxima reunión:

![17_nov_new_filaments_and_parts](https://user-images.githubusercontent.com/6171234/48676645-d4dac280-eb69-11e8-8050-7923e84951f2.jpg)
