### ISSUE TITLE
Reestructuración carpetas de impresoras

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#104]
Actualmente las carpetas de las impresoras contienen muchísima información valiosa que, por desgracia, es inútil porque nadie sabe qué es qué. Además está mezclada información importante con otra que ya no es necesaria. Ejemplos:
- En negro, archivos obsoletos.
- En rojo, archivos desactualizados.

![sin titulo](https://user-images.githubusercontent.com/6171234/46916517-2799eb00-cfbc-11e8-8f27-3855847d81cb.png)

Ahora que estamos a punto de implantar Octoprint, propongo actualizar esto y crear una estructura de carpetas del estilo:

- [Nombre Impresora]
  - Slic3r
  - Marlin
  - Linux
  - Otras...

Por otra parte, la carpeta Parts corre el riesgo de crecer de forma descontrolada, por lo que propongo subdividirla con nuevas carpetas para facilitar la localización de las piezas (ver Carpeta de Hija Resurrection: 0363e391158485261eb205cfc239e86b738a5702 ).

**Comment by GioSunrider** [comment]
Me parecen geniales todas la ideas, cuanto más colocado y documentado, mejor. Más facilidad de encontrarse y de arreglar en caso de fallo.

**Comment by d-marcos-m** [comment]
voy a hacer una reestructuración rápida con la idea de @Siotma y vemos qué más cambios podemos hacer :)

**Comment by d-marcos-m** [comment]
Hecho, echadle un vistazo. Habrá que revisar de todas formas todos esos archivos .ini y probablemente actualizarlos, porque hay varios que seguramente no sepamos ni lo que son :sweat_smile:

**Comment by GioSunrider** [comment]
Ya de paso, si encuentramos tiempo desde casa actualizar el código del nuevo marlin a todos los ficheros para cuando lleguemos a la reunión solo haga falta subirlo. 

Buen trabajo @dmarcosm

**Comment by GioSunrider** [comment]
Se ha procedido al cambio de Carpetas y a la reestructuracion, muy buen trabajo, @Siotma y @dmarcosm , cerrad alguno la issue que os lo ha beis ganado.
