### ISSUE TITLE
Las solicitudes de operador no se están respondiendo

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#108]
Ejemplo:
https://github.com/asrob-uc3m/operadores/issues/42
26 días sin respuesta.

**Comment by d-marcos-m** [comment]
Están en el grupo de impresoras y cuando lo han comentado se les ha dicho que hasta que no haya varias funcionales no es posible hacerlo (hace 2 semanas). Sí es verdad que ahora mismo ya funcionan tanto la Anet como Hija y se podría hacer la formación.

**Comment by GioSunrider** [comment]
Ahora mismo hay muchas Impresoras operativas, para los pertenecientes al grupo de printer se están realizando las formaciones simultáneamente que las reuniones en función de necesidad. Habría que ver si las heredadas del año pasado siguen interesados en la formación.

**Comment by GioSunrider** [comment]
He realizado una pregunta general a todos los implicados para ver si siguen o no interesados, si no recibo respuesta en un par de semanas cerrare sus respectivas issues. Si siguen interesados ya buscaremos forma de realizarles la formacion.
