### ISSUE TITLE
Comprar piezas necesarias para extrusores geared

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#110]
Hoy se han comprado piezas para hacer nuevos extrusores geared:
- 6x [rodamientos 608Z](https://fervi3d.com/mecanica/154-rodamiento-608zz-8x22x7mm.html)
- 2x [hobbed bolt](https://fervi3d.com/extrusion/156-tornillo-ranurado-extrusor-m8.html)
- 1x [varilla M8 lisa 200mm](https://fervi3d.com/extrusion/156-tornillo-ranurado-extrusor-m8.html)

**Comment by GioSunrider** [comment]
Cuando puedas @Siotma podrías añadir los enlaces?

**Comment by Siotma** [comment]
Hecho

**Comment by GioSunrider** [comment]
Muchas gracias!

**Comment by Siotma** [comment]
Las piezas llegaron hace unos días. Las llevaré en la próxima reunión:

![17_nov_new_filaments_and_parts](https://user-images.githubusercontent.com/6171234/48676645-d4dac280-eb69-11e8-8050-7923e84951f2.jpg)
