### ISSUE TITLE
Hacer ballestas

### ISSUE THREAD

**Issue by VentressAsajj** [asrob-uc3m/impresoras-asrob#112]
Me acordé de ponerlo @GioSunrider @dmarcosm ¿cuándo hacemos las ballestas? 
Tweet:
https://twitter.com/fisadev/status/1059631656250806274
Thingiverse:
https://www.thingiverse.com/thing:1995091
Cómo montarla
https://t.co/8zYOswTtnr

**Comment by GioSunrider** [comment]
Organizamos un taller de ballestas 😂😂

**Comment by VentressAsajj** [comment]
Vamos. Cuando es la próxima reunión de printerone? yo tengo que ser operadora, debo poner otra issue ( como digas que sí te mato jajaja )

**Comment by MrTommyGuns** [comment]
La próxima reunión es Jueves de 6 a 9

**Comment by MrTommyGuns** [comment]
Y para solicitar la formación como operadora y demás...
Si, hay que poner otra issue 😅😅
Peroo no es en este grupo de trabajo, te adjunto el link.

http://GitHub.com/asrob-uc3m/operadores/issues

**Comment by GioSunrider** [comment]
Eso es sigue lo que te ha dicho Tommy, vivan las issues 🤣🤣

**Comment by d-marcos-m** [comment]
> Vamos. Cuando es la próxima reunión de printerone? yo tengo que ser operadora, debo poner otra issue ( como digas que sí te mato jajaja )

El jueves las imprimimos!!

**Comment by VentressAsajj** [comment]
Pues si el jueves se imprimen, no creo que sea necesario hacer el curso intensivo de operadora ni poner la puuuññññetera issue :joy:

**Comment by d-marcos-m** [comment]
Imprimir las piezas de la ballesta te vale como parte de la formación de operadora :)

**Comment by jorgercobo** [comment]
Primer intento de impresión 
![image](https://user-images.githubusercontent.com/9537923/48646752-0a58a200-e9ea-11e8-9e8b-69d6cf2ee39d.png)

Falta una de las piezas laterales y los tornillos por imprimir

**Comment by jorgercobo** [comment]
Falta una de las piezas laterales y los tornillos
