### ISSUE TITLE
Nuevo carro para Blacky

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/impresoras-asrob#113]
Vamos a ponerle a Blacky el carro que ya está funcionando en Hija #84 

- 3 piezas del [L3Kv2](https://www.thingiverse.com/thing:1855673):
  - [x] [1x Wade_L3K_v2_Idler.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393904/Idler.zip)
  - [x] [1x Wade_L3K_v2_Idler_hodler.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393905/Idler_hodler.zip)
  - [x] [1x Bearing_Washer.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393911/Bearing_Washer.zip)

- 2 piezas Remix del [L3K](https://www.thingiverse.com/thing:512338), pero diseñado para poder meter el tubo de teflón hasta el Barrel:
  - [x] [1x Wade_L3K_custom_flange_1.75_v2_mirrored.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2394024/Wade_L3K_custom_flange_1.75_v2_mirrored.stl.zip)
  - [x] [1x Wade_L3K_custom_body_1.75_centered.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2384181/Wade_L3K_custom_body_1.75_centered.stl.zip)

- Creación propia:
  - [x] [1x Body_E3dv6_Washer.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393912/Body_E3dv6_Washer.zip)
  - [x] Extra ventilador de capa: [1x Blower_duct.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2394029/Blower_duct.zip)

Que empiece el reto!

**Comment by GioSunrider** [comment]
Algún voluntario para imprimirlo en casa? Es necesario imprimirlo en casa dado que el tiem po de impresion excede el tiempo de cualquier reunion normal.

**Comment by GioSunrider** [comment]
Imprimiendo todo en Hija y Blacky

**Comment by GioSunrider** [comment]
Blacky imprimio su propio Duct como muestra la foto.

![photo5787469200615387082](https://user-images.githubusercontent.com/10605193/49646819-a5a8ca00-fa20-11e8-9cd1-301eacc78349.jpg)

E hija imprimioo el resto de piezas, hubo una pequeña perdida de pasos, se valorara si la piezas sirven o no en la siguiente reunion. 

![photo5787469200615387081](https://user-images.githubusercontent.com/10605193/49646865-c83ae300-fa20-11e8-82b2-0b6c950aa146.jpg)

**Comment by GioSunrider** [comment]
Se ha reimpreso el boddy ya que se sufrio un desplazamiento de capa y no quedo bien alineado. el resto de piezas se pueden usar sin problemas.
Cierro issue y abro una nueva para el cambio de extrusor, ya que se comenzo con el cambio.
