### ISSUE TITLE
Cambio extrusor para Geonosis

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/impresoras-asrob#114]
Se ha decidido cambiar el extrusor de Geonosis a un v6 con bloque Volcano de nozzle 1,2. Para ello se necesitan las siguientes piezas:

- 3 piezas del [carro](https://www.thingiverse.com/thing:2865870):
  - [x] [1x Duct.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2586589/Duct.stl.zip)
  - [x] [1x CR-10_HD-modular-mount-V6_mount-cover__40mm-fan_v1.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2586593/CR-10_HD-modular-mount-V6_mount-cover__40mm-fan_v1.stl.zip)
  - [x] [1x v6_mont_x5s_v4.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2586594/v6_mont_x5s_v4.stl.zip)
  - [x] [1x autolevel.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2586587/autolevel.stl.zip)

[EDIT]

- [x] [Duct Volcano](https://www.thingiverse.com/thing:3265261)

**Comment by GioSunrider** [comment]
Imprimiendolo en casa para ver si esta tarde lo puedo llevar para comenzar su montaje.

**Comment by Siotma** [comment]
Imprimiendo el duct en Hija.

**Comment by jorgercobo** [comment]
Se ha comenzado a montar el carro, pero hay un problema con las tuercas traseras. Pendiente de volver a montarlo en la siguiente reunión

**Comment by jorgercobo** [comment]
![photo_2018-11-27_21-10-01](https://user-images.githubusercontent.com/9537923/49108589-da7e8980-f288-11e8-8f72-e9a6930785e7.jpg)

**Comment by GioSunrider** [comment]
Se imprimio en Blacky el soporte del Autolevel, ya que, como se ve en la foto, es donde tambien va colocado el End-Stop. 

![photo5783078558627901266](https://user-images.githubusercontent.com/10605193/49646755-65494c00-fa20-11e8-8f9a-876a83f3c18e.jpg)


![photo5787469200615387084](https://user-images.githubusercontent.com/10605193/49646199-afc9c900-fa1e-11e8-8222-a7658be21fdb.jpg)

Ademas como se ven en la foto anterior se termino de colocar el resto del extrusor a falta de colocar el ventilador de capa, el cual se realizo el cambio y se soldó. 

![photo5787469200615387083](https://user-images.githubusercontent.com/10605193/49646673-14395800-fa20-11e8-8903-f2be02d27603.jpg)

No se pudo colocar, ya que el Duct no esta adaptado para la cabeza Volcano, para ello, he diseñado una [pieza nueva para poder poder el ventilador](https://www.thingiverse.com/thing:3265261)
El proximo dia se imprimira y se colocara.

**Comment by GioSunrider** [comment]
Hija imprimio sin problemas el nuevo Duct, pero por error mio de diseño no queda bien, dado que ahora me he pasado de tamaño. En la proxima reunion llevare el duct bien puesto para que geonosis  pueda comenzar a imprimir. Adjunto fotos del proceso.

![photo5809819690732728211](https://user-images.githubusercontent.com/10605193/50008556-dd7db780-ffb4-11e8-9226-590658b967b7.jpg)

![photo5809819690732728212](https://user-images.githubusercontent.com/10605193/50008566-e078a800-ffb4-11e8-98f8-8700c854fbb4.jpg)

**Comment by GioSunrider** [comment]
En la pasada reunion lleve el nuevo duct, esta vez, con los cambios necesarios. Se instalo y quedo perfecto. por lo que queda como satisfactorio el cambio de extrusor.

![photo5825418127188537375](https://user-images.githubusercontent.com/10605193/50283138-4a7dcb00-0455-11e9-8481-6ff1f28c3448.jpg)

**Comment by JorFru** [comment]
El nozzle actualmente instalado en geonosis, aunque en su inscripción lateral se puede leer claramente 1.2, este nozzle es de 0.8mm aunque Giorgio diga lo contrario.
El calibre digital chino dicta que son 0.8, y los chorretes que suelta miden 0.8 también.
conclusión: 0.8
