### ISSUE TITLE
Instalar nuevos muelles en Dédalo

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#116]
En la última reunión, @madelgj y @CeciliaVa instalaron los muelles comprados en #103 en Dédalo. Quedaron muy bien y realmente han mejorado la estabilidad de la base de impresión. Debido a #115, habrá que desmontarlos y volver a ponerlos, pero el crédito es para ellas de cualquier manera así que pueden cerrar la issue.

Para muestra una foto:

![27_nov_dedalo_base_springs](https://user-images.githubusercontent.com/6171234/49309772-a1d6ee00-f4dc-11e8-9114-35f770b8c6ee.jpg)

**Comment by CeciliaVa** [comment]
Hoy @MrTommyGuns, @CinnabarCinnamon y yo, con la colaboración de @DiegoGarciaX2, tras reajustar la dirección del eje Y y tensar la correa de ese mismo eje (#115) hemos colocado los nuevos muelles y calibrado a Dédalo :smiley: :tada:

**Comment by GioSunrider** [comment]
Dado que los muelles quedaron bien instalados tras #115 que alguno de los implicados cierres la issue por favor.
