### ISSUE TITLE
Instalar nuevos muelles en Blacky

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#117]
En #103 se compraron nuevos muelles. Están en el armario. Tareas:

- [x] Sustituir los muelles que tiene Blacky actualmente en la cama caliente por los nuevos.
- [x] Nivelar la cama caliente de Blacky.

**Comment by CinnabarCinnamon** [comment]
Nuevos muelles instalados. Los antiguos se han guardado en la caja "RODAMIENTOS".
Cama nivelada. Se puede imprimir.
![whatsapp image 2019-01-18 at 19 05 33](https://user-images.githubusercontent.com/44849400/51404920-247f3f80-1b55-11e9-86a3-634b3e42dacf.jpeg)
![whatsapp image 2019-01-18 at 19 05 43](https://user-images.githubusercontent.com/44849400/51404921-247f3f80-1b55-11e9-8b65-99b11892186e.jpeg)
