### ISSUE TITLE
Instalar nuevos muelles en Hija Resurrection

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#118]
En #103 se compraron nuevos muelles. Están en el armario. Tareas:

- [x] Sustituir los muelles que tiene Hija Resurrection actualmente en la cama caliente por los nuevos.
- [x] Nivelar la cama caliente de Hija Resurrection.

**Comment by CinnabarCinnamon** [comment]
Muelles sustituidos. Cama nivelada.
Se ha adherido el cartón a la cara inferior de la cama.
Se puede imprimir.
![whatsapp image 2019-01-18 at 20 50 19](https://user-images.githubusercontent.com/44849400/51410210-34525000-1b64-11e9-9b09-6c02ff747829.jpeg)
![whatsapp image 2019-01-18 at 20 50 40](https://user-images.githubusercontent.com/44849400/51410211-34eae680-1b64-11e9-9a75-900304863f5e.jpeg)
