### ISSUE TITLE
Cambio de extrusor Blacky

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#119]
Viene de #113, pese a los problemas que se citan ahi, en la ultima reunion se comenzo el cambio de extrusor, desmontando el anterior. Blacky queda en el estado de la foto hasta la proxima reunion que llevare las piezas que faltan.

![photo5809819690732728210](https://user-images.githubusercontent.com/10605193/50008391-52042680-ffb4-11e8-8ecb-b6d109d788d4.jpg)

**Comment by GioSunrider** [comment]
En la ultima reunion se termino de colocar el nuevo extrusor de Blacky. Tambien se coloco el ventilador de capa. por lo que esta issue se da por cerrada.

![photo5825418127188537374](https://user-images.githubusercontent.com/10605193/50282775-2ec5f500-0454-11e9-89c0-1ceca703f82f.jpg)

**Comment by GioSunrider** [comment]
Solo faltaria calibrarla, recomiendo hacerlo despues de cambiar los muelles de la cama.
Y realizar pruebas de impresion.

**Comment by Siotma** [comment]
En la última reunión se detectó que el ventilador de capa de Blacky se había partido. Aprovechando que diseñé una segunda versión del que tenía, imprimimos esa. Dejo la pieza aquí. He detectado que la carpeta Parts de Blacky está casi vacía: #121

[Blower_duct_v2.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2751967/Blower_duct_v2.zip)
