### ISSUE TITLE
Documentar las piezas de Blacky

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#121]
La carpeta de piezas de Blacky (https://github.com/asrob-uc3m/impresoras-asrob/tree/master/Blacky/Parts) está actualmente casi vacía y muy desactualizada. Teniendo en cuenta que recientmente se ha instalado un nuevo extrusor (#119) se debería aprovechar para actualizarla. 

P.D.: Nótese que el nuevo ventilador de capa es la V2 que he dejado [aquí](https://github.com/asrob-uc3m/impresoras-asrob/issues/119#issuecomment-453742406)

**Comment by CinnabarCinnamon** [comment]
Se ha subido los archivos .stl de varias piezas de extrusor y LCD de Blacky a la carpeta Parts.
