### ISSUE TITLE
Tensores Spicy X e Y

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#123]
En la ultima reunion, aprovechando que #122 vino con el Tensor del eje Y, se desmonto e instalo en spicy, dando como resultado la siguiente imagen.

![photo5897758450333626265](https://user-images.githubusercontent.com/10605193/51086934-ed6fef00-174c-11e9-97da-4b3542f91fe6.jpg)

El siguiente paso a recorrer seria la discusion, impresion e instalacion del tensor del eje X, por lo que propongo el siguiente proceso:

- [x] Discusión sobre que tensor colocar

- [ ] Impresion del Tensor

- [ ] Colocacion del Tensor

**Comment by CinnabarCinnamon** [comment]
Piezas encontradas para tensor:

[X-axis-Right_2017.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842201/X-axis-Right_2017.zip)
[BIG-thumbscrew.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842202/BIG-thumbscrew.zip)
[pulley-Toothed_bearing.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842203/pulley-Toothed_bearing.zip)
[tensioner-Thick.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842204/tensioner-Thick.zip)

**Comment by GioSunrider** [comment]
ya que hay que imprimir, imprimiremos mejor la misma pieza que lleva [Hija](https://github.com/asrob-uc3m/impresoras-asrob/tree/master/Hija%20Resurrection/Parts/X%20axis)

**Comment by CinnabarCinnamon** [comment]
La pieza impresa sirve para Blacky, NO para Spicy.

**Comment by GioSunrider** [comment]
Sigue para Blacky en #136

**Comment by GioSunrider** [comment]
Para no tener que imprimir una pieza nueva del eje X, propongo el siguiente [tensor](https://www.thingiverse.com/thing:3078070) asi ni necesita sustitucion de correa por ser demasiado pequeña ni una piezaq entera nueva. El proximo dia, podemos imprimir y colocarlo.

**Comment by MrTommyGuns** [comment]
Adjunto Link para imprimir un tensor bien hot.
https://www.thingiverse.com/thing:1428253

**Comment by L4g0** [comment]
Instalado tensor eje X :smile: 
![image](https://user-images.githubusercontent.com/23212123/53593196-5940d680-3b98-11e9-8a15-48a025026ede.png)
