### ISSUE TITLE
Ventilador de capa Dédalo

### ISSUE THREAD

**Issue by CinnabarCinnamon** [asrob-uc3m/impresoras-asrob#125]
El ventilador de capa de Dédalo produce un error de thermal runaway, habrá que hacer otro diseño o inventar algo para colocarlo de manera que apunte a la pieza.

**Comment by GioSunrider** [comment]
Voy a expandir un poco la idea. El ventilador de dedalo no apunta a la capa, si no al Hot-End y por eso cuando lo hemos conectado en mitad de la impreson ha producido el error.

**Comment by CinnabarCinnamon** [comment]
Gracias a Víctor por su aportación, tenemos piezas para el ventilador.
[piezaventilador2.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2890573/piezaventilador2.zip)
[pieza centilador.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2890574/pieza.centilador.zip)

**Comment by GioSunrider** [comment]
Resulta que hemos encontrado una colocacion mejor y hemos usado la misma pieza pero sin dimensionar.

https://www.thingiverse.com/thing:823412/files

**Comment by GioSunrider** [comment]
Tampoco vale esa pieza, así que he optado por rediseñarla. El carro ha quedado medio desmontado así que queda fuera de servicio hasta su finalización.

![img_20190228_203413](https://user-images.githubusercontent.com/10605193/53606116-ec3e3880-3bb9-11e9-8c94-c7b0ba030eec.jpg)

**Comment by GioSunrider** [comment]
He rediseñado unas piezas para el ventilador. Se encuentran publicadas en el siguiente enlace:
https://www.thingiverse.com/thing:3618964
Solo hay que imprimir y colocarlo.

**Comment by GioSunrider** [comment]
Se ha dejado en Spicy imprimiendo el Ducto, quedarian pendientes las otras dos piezas.

**Comment by CeciliaVa** [comment]
![IMG_20190703_195955](https://user-images.githubusercontent.com/36002031/60620366-4dca1a00-9ddb-11e9-8516-66faaee25981.jpg)
:sparkles: Ahora la correa ha quedado bien puesta y el ventilador de capa perfectamente instalado. :sparkles:
