### ISSUE TITLE
Video 1. Presentacion de la granja

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#127]
En esta issue reflejaremos el guion y la produccion del video de presentacion de la granja, asi como el material audiovisual del mismo.

**Comment by GioSunrider** [comment]
Imagenes de las impresoras para utilizar.

https://drive.google.com/file/d/1Esr2Bw1mX4VhRgQrtKhgr3Jn0qyi5ILj/view?usp=sharing

**Comment by L4g0** [comment]
## Guión 

¡Hola! Bienvenidos al curso de manejo e impresión 3D de asrob uc3m.

Para empezar os vamos a presentar a nuestras máquinas.

Del proyecto Clone Wars han nacido **Hija Resurrection**, **Blacky** y **Dédalo**

La primera es una prusa i3 steel (más info [en la descripición](http://wiki.asrob.uc3m.es/index.php/RepRap:_HIJA)). Actualmente se encuentra con un nozzle de 0.5 mm para filamento de 1.75 mm.

La segunda se trata de una Prusa Air 3 (más info [en la descripición](http://wiki.asrob.uc3m.es/index.php/RepRap:_BLACKY)). Actualmente se encuentra con un nozzle de 0.5 mm para filamento de 1.75 mm

**Dédalo** se trata de una Prusa i2. Esta es la única de nuestras impresoras que utiliza filamento de 3 mm (más info [en la descripición](https://www.reprap.org/wiki/File:Clon-28-Dedalo.jpg)). Actualmente se encuentra con un nozzle de 0.4 mm para filamento de 3 mm

**Geonosis** es la última de nuestras adquisiciones. Es un modelo TronXY X5S y es la única impresora CoreXY que tenemos por el momento. Actualmente se encuentra con un extrusor Volcano de 1.2 mm de nozzle. Utiliza filamento de 1.75 mm. Además, es la única con sistema Bowden.

**Spicy** (caldito para los amigos) es el conocido modelo Anet A8, adquirida a través de una donación. Actualmente se encuentra con un nozzle de 0.4 mm para filamento de 1.75 mm

En los siguientes vídeos os enseñaremos cuál es su correcta utilización.
