### ISSUE TITLE
Charla Impresoras 3D en Jornadas Técnicas del GUL

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#135]
Hola, abro issue para pedir préstamo.

Me he presentado para dar una charla en las JT del GUL https://cursos.gul.es/xxxiii-jornadas-tecnicas-del-gul

Me gustaría llevar a la charla a Dédalo, para que los asistentes vean las abominaciones mecánicas que se construían con pocos recursos, a fin de calmar el SAV.
El objetivo es llevarla para enseñar, quizás ponerla a imprimir pero sería raro.

Más datos: jueves 18 febrero, de 16 a 18h, 1.1.G04.
Si alguien se anima a ayudarme con la charla, invitado está.

**Comment by GioSunrider** [comment]
Ahora mismo dedalo no puede imprimir a falta de terminar su cable managment. Por el prestamos sin problema, yo mismo puedo echarte un cable con la charla si lo necesitas.

**Comment by JorFru** [comment]
Okey, gracias por la info y el ofrecimiento.
Continuamos la colaboración por chat privado.
Si alguien más se anima que se manifieste

**Comment by David-Estevez** [comment]
>  las abominaciones mecánicas que se construían con pocos recursos, a fin de calmar el SAV.

:unamused:

**Comment by GioSunrider** [comment]
Dejo aqui la foto del evento con dedalo habiendo acabado de imprimir y @JorFru exponiendo de fondo.

![1bd5d862-c37b-45de-84c4-d409dc85263e](https://user-images.githubusercontent.com/10605193/53452280-24f6da00-3a21-11e9-8fb4-58983822cf90.jpg)

**Comment by JorFru** [comment]
Aquí dejo la documentación generada
https://github.com/JorFru/Charlas/tree/master/JornadasT%C3%A9cnicasGUL/XXXIII

Desde aquí otra vez agradecer a Coleóptero, Obijuan y todo Clone Wars.
Sobre todo por la cantidad de diapositivas que dejaron de sus charlas anteriores y he podido reutilizar.
