### ISSUE TITLE
Mejoras Spicy

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#137]
Abro esta issue para ir documentando y mejorando a Spicy.

Propongo esta página para ir mirando las mejoras: https://www.staticboards.es/blog/mejoras-anet-a8/

- [ ] Botón para encendido. _(@JorFru approves)_

- [ ] Mejora estructura eje X.

- [x] Tensor eje X. _(Issue #123 )_

- [x] Final de carrera Z.

- [ ] Aros para muelles cama caliente.

- [ ] Reforzar interior delantero.

- [ ] Reforzar interior trasero.

- [ ] Soldar cables directamente a la cama. _(@JorFru approves)_

- [x] Cambiar soporte ventilador carro https://github.com/asrob-uc3m/impresoras-asrob/issues/153

- [ ] Cambiar el conjunto caliente por un V6

**Comment by GioSunrider** [comment]
En la reunion de ayer se imprimió e instalo la mejora del final de carrera del Eje Z.

**Comment by MrTommyGuns** [comment]
Si no recuerdo mal, en la reunión de ayer @JorFru y yo comentamos la posibilidad de ponerle un extrusor nuevo a Spicy y chetarla un poquete ya que tenemos extrusores para cambiar en el armario.

Esto podría ser una mejora bastante guay para Spicy.

**Comment by GioSunrider** [comment]
A mí modo de ver prefiero que el extrusor bondtech del armario vaya para blacky o geonosis, y me decanto más por geonosis, ya que el motor sufre mucho y ponerle la reductoras ayudara a este problema
