### ISSUE TITLE
El bote de laca está vacío.

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#14]
Pues eso. Si lo que tenemos en la nave es ABS, un bote de laca es primordial.

**Comment by David-Estevez** [comment]
El rollo amarillo de la nave es ABS, comprobado al 100% por mi.

**Comment by jgvictores** [comment]
Yo disponía de un bote pequeño de laca, pero le faltaba la pieza de salida (plástico blanco difusor). He donado este bote y le he puesto la pieza de salida del bote grande vacío. Ahí queda en la nave para su uso con las impresoras de ASROB.

![photo_2017-02-09_10-21-00](https://cloud.githubusercontent.com/assets/4448588/22776848/820c1ede-eeb1-11e6-9dff-dd077baa5b40.jpg)
