### ISSUE TITLE
Soporte de filamento para Spicy

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#141]
Hace unos meses el soporte para filamento de Spicy murió.
El tema está en que tenemos varias impresoras que imprimen correctamente y nos faltan soportes si las queremos poner a imprimir todas.
Sugiero la siguiente pieza para hacerle un soporte:

https://www.thingiverse.com/thing:2162266

Por el momento la he impreso para mi anet y parece que funciona correctamente.

**Comment by MrTommyGuns** [comment]
Si lo hacemos, sugiero ponerle una capa de pegamento caliente fina como antideslizante y la estabilidad mejora una barbaridad

**Comment by GioSunrider** [comment]
Buena idea, se esta imprimiendo en Hija ahora mismo.

**Comment by MrTommyGuns** [comment]
En la tarjeta de hija está el gcode del soporte y los conos están en la de Spicy, por si queréis reutilizarlos...
A los conos les faltaba poner algo más de relleno

**Comment by GioSunrider** [comment]
he borrado la tarjeta entera... eso no se deja ahi...

**Comment by GioSunrider** [comment]
Se han impreso las dos piezas, una vez se coloquen se subira la foto y quedara por cerrada la issue.

**Comment by JorFru** [comment]
![photo_2019-05-09_22-01-29](https://user-images.githubusercontent.com/11017088/57483031-5522ea80-72a6-11e9-9068-123a7b78748b.jpg)

**Comment by JorFru** [comment]
Mejoras de pegamento caliente por @MrTommyGuns
