### ISSUE TITLE
Conos para filamento

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#143]
Creo muy conveniente que imprimamos una serie de conos, tubos o lo que sea para centrar los filamentos en los soportes.

En mi opinion son más útiles los conos porque se adapta a los tropecientos tipos de bobinas que tenemos, pero es más engorroso colocarlos si no se plantea el mecanismo adecuadamente.

Ejemplo: [CONO](https://www.thingiverse.com/thing:767317)

Se aceptan sugerencias.

**Comment by fervh** [comment]
[cono.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/3768816/cono.zip)

**Comment by MrTommyGuns** [comment]
Finalmente se realizó la impresión de 2 de estos [conos](https://www.thingiverse.com/thing:767317)

![conos](https://user-images.githubusercontent.com/36898802/69825553-f99f5680-120f-11ea-9faf-5d5efc389f3a.jpg)

Creo que al menos deberíamos hacer un par más.
