### ISSUE TITLE
Cambio de Llaves

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#147]
Solicito a @Siotma que un dia se acerque y haga un cambio de llaves a @MrTommyGuns ya que va a ser el segundo responsable del grupo.

**Comment by Siotma** [comment]
Las llaves se entregaron el día 11 de septiembre, tal y como consta en https://github.com/asrob-uc3m/actas/issues/201

Queda pendiente actualizar la web para que conste el nuevo propietario de las llaves.

El seguimiento de las acciones pendientes se continuará en el repo de actas, que es donde debe hacerse.
