### ISSUE TITLE
Uso de filamento por los operadores

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#150]
Deberíamos resolver cuanto antes el problema/dilema de la cantidad de plástico de la asociación usado por los operadores.

La mejor opción yo diría que es poner limites en los gramos de las impresiones, de tal modo que si se utiliza este plástico no sea de forma abusiva para un uso personal.

A parte de eso habría que poner un límite en el cual se dejará de poder imprimir con el plástico de forma personal (punto para dar una palmadita en el hombro y decirle al susodicho que se gaste 10€ y compre una bobina xD).

**Comment by GioSunrider** [comment]
Esto creo que iría mejor en actas. Y de hecho creo que ya hay issue, aunque esté cerrada.

**Comment by jgvictores** [comment]
> Esto creo que iría mejor en actas. Y de hecho creo que ya hay issue, aunque esté cerrada.

Síp, era la intención de https://github.com/asrob-uc3m/actas/issues/61. Aunque se trate de lo mismo, me gusta más cómo se plantea el problema aquí. Si lo queréis mover, ahí está el botón de `Transfer issue`. :smiley:

**Comment by MrTommyGuns** [comment]
Teniendo en cuenta como se está llevando finalmente este asunto, creo que hemos dado con una buena dinámica.
A todos los nuevos operadores se les ha dicho que para imprimir lleven su propio filamento en el caso que sea para uso personal.
Si es para uso interno de la asociación, ya sean mejoras para las impresoras, proyectos de otras ramas... Se usará el filamento de la asociación.
Como siempre, puede que haya situaciones en las que se pueda usar el filamento de la asociación para uso personal, siempre que sea de manera puntual, haya algún punto de interés y/o se compense por otro lado (casos más concretos, que a mi parecer tampoco pasa nada).
Pero dejaría cerrado el asunto con esta propuesta si os parece bien.

**Comment by GioSunrider** [comment]
A mi me parece lo correcto.

**Comment by David-Estevez** [comment]
![image](https://user-images.githubusercontent.com/1451819/69760502-fe5b0080-1164-11ea-9af8-2d8fccfcbdd0.png)

**Comment by jgvictores** [comment]
Opino lo mismo. Parece buena idea, pero tb parece una cosa muy horizontal.

Mejor una PR sobre estatutos, y votar sobre el merge.

Como pequeño aporte: ¿Quizás alguna cláusula de pago comisión en fungible? No sé, si alguien va a pulirse 5-10 bobinas, pues tal vez tenga sentido que aporte 1 bobina a la Asociación por compensar desgaste o algo.

**Comment by GioSunrider** [comment]
Creo que actualmente nadie trabaja a ese volumen, el grupo de primer es quizá el que más hasta y tenemos filamento que nos va a durar años

**Comment by jgvictores** [comment]
Nos han llegado a pedir ciertos trabajos de elevado volumen y siempre se quedó en el aire debido al vacío en cuanto a estatutos.

**Comment by GioSunrider** [comment]
Yo creo que ese tipo de trabajos deberian de aportar su propio plastico. Y se regirian por lo mismo motivo de los operadores de uso personal.

**Comment by MrTommyGuns** [comment]
Estoy de acuerdo, deberían de llevar su material y/o darnos la pasta para pillar el material necesario para hacer lo que sea

**Comment by jgvictores** [comment]
Lo que comentaba era respecto a un % adicional proporcional al utilizado, para compensar por el uso/desgaste/mantenimiento de las impresoras como tal.

**Comment by GioSunrider** [comment]
Ahhh vale vale, ya lo entinedo, y tambien me parece correcto. Ya que somos quienes las mantenemos y cuesta horas de trabajo tenerlas a punto.
