### ISSUE TITLE
Cambio de Placa de Control de Hija

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#151]
Como se comentó en #149 hija murió y vamos a cambiar la placa de control. Seguiremos documentando en esta issue.

**Comment by GioSunrider** [comment]
Se va a aprovechar a hacer #79 ya que hay que revisar todo.

**Comment by MrTommyGuns** [comment]
Finalmente se realizó el cambio de placa e hija queda finalmente funcional.
Se observó que los motores no estaban correctamente sujetos, lo cual provocaba que fallaran, se desmontaron y montaron, quedando funcionales, pero potencialmente pueden volver a fallar.
Queda pendiente imprimir una caja en condiciones para la placa.
Gracias a todos los que metieron mano para dejarla on point.
