### ISSUE TITLE
Nueva incorporacion a la familia.

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#152]
Tal y como se dijo en [actas](https://github.com/asrob-uc3m/actas/issues/197) y aunque no hay hueco todavia para su uso, tenemos una nueva incorporacion.
Los detalles de la impresora se encuentran en la otra issue pero hay que seguir unos pasos para "darle de alta" en nuestro sistema.
Los pasos son:

- [ ] Hoja de Reserva

- [ ] Ponerle nombre

- [ ] Colocarla en su sitio definitivo

[MORE]

- [ ] Instalacion con Rpi junto con Spicy para Octoprint.

A su vez empieza la gestion, empezar a proponer nombres para ella. Daremos un tiempo de margen y comenzara el resto.

**Comment by GioSunrider** [comment]
En la reunion de ayer, realizamos una colocacion que parece ser la definiva para comenzar su uso hace falta colocar una rpi para añadirle octoprint.

**Comment by MrTommyGuns** [comment]
En la ultima reunión se recolocaron algunas impresoras, incluida esta dotandola de un espacio aparentemente definitivo.

Se realizó una prueba de impresión y a pesar de que la primera capa fue un fracaso la pieza remontó con un resultado bastante bueno.
