### ISSUE TITLE
Nombre para la nueva incorporacion

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#155]
Como se establece en #152 tenemos que poner un nombre la nuestra pequeña, asi que que comiencen las propuestas.

**Comment by David-Estevez** [comment]
Suegra

**Comment by GioSunrider** [comment]
- Moeby Dick

- Moby Dick

**Comment by MarioPrinter** [comment]
**NOMBRES PROPUESTOS:**
- Moeby Dick
- Moby Dick
- Suegra
- Flashy
- White
- Mr White
- Whity
- Little sister (y a la cube pro Big Daddy)
- Maincra

**Comment by David-Estevez** [comment]
Blancanieves (o Snow White si os sentís internacionales)

**Comment by Petikuis** [comment]
A mi me gusta la de Moeby Dick

**Comment by GioSunrider** [comment]
Abierta votacion en https://forms.gle/h8whnzjjYJ5YPVbS8 os dejo una semanita.

**Comment by JorFru** [comment]
Bueno ¿cómo va esto?

**Comment by GioSunrider** [comment]
Y cerramos el año con el nuevo nombre decidido. Moeby Dick ha sido el ganador. Procedere a los tramites para incorporarla en todos los lados.
![image](https://user-images.githubusercontent.com/10605193/71619244-c3187b00-2bc3-11ea-8d19-ca905f3af016.png)
