### ISSUE TITLE
Hija no imprime en ABS

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#157]
Cuando se intenta calentar a Hija con la suficiente temperatura da error en el extrusor.
Deberíamos mirar porqué puede ser... Tal vez sea cosa del marlin que esté capado a modo de seguridad para que no se caliente en exceso.

![photo_2019-12-06_22-57-47](https://user-images.githubusercontent.com/36898802/70359299-e0d01a00-187b-11ea-9541-ed50685f0d0d.jpg)

**Comment by JorFru** [comment]
también habría que ponerle una funda de siicona "calcetín", ya que hija está equipada con un bloque caliente tipo E3D V6 y en el armario tenemos calcetines de sobra.
Pero lo que dice Tommy tiene toda la lógica.
