### ISSUE TITLE
Movimiento X Geonosis

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#158]
He estado poniendo a punto a Geonosis.

Para ello he estado ajustando los pasos/mm de la impresora y actualizando el marlin (cuando funcione todo correctamente lo subiré).

El problema reside en que el eje X se mueve en vertical y no tengo la más mínima idea de porqué puede ser, ya que el eje Y que funciona con el mismo mecanismo funciona a la perfección, pero he sido incapaz de configurar el eje X.

**Comment by jgvictores** [comment]
Entiendo q cerrado via https://github.com/asrob-uc3m/impresoras-asrob/issues/160 : )
