### ISSUE TITLE
Refuerzo Estructura Spicy

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#159]
Hay que investigar en el siguiente link cual son las piezas que le valen a Spicy para posteriormente imprimirlo ya que considero que es una mejora que dota a la impresora de una notable rigidez, que falta le hace.

[Anet A8 Brackets to Reduce X-Axis Motion](https://www.thingiverse.com/thing:1872162)

**Comment by GioSunrider** [comment]
Personalmente no recomiendo esta mejora, la quite de la impresora, no da mucha mas estabilidad y es muy engorrosa, recomiendo mejor esta otra.

https://www.thingiverse.com/thing:1672959
