### ISSUE TITLE
El bote de laca ha desaparecido

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#17]
Esto es un serio problema, ya que es de los pocos recursos de la asociación que se dejan fuera del armario...

Hasta hoy no recuerdo que hubiera pasado nunca, pero ayer ya no estaba, y no lo encuentro en ningún armario.

**Comment by David-Estevez** [comment]
El bote se lo dejé yo el otro día a los del departamento, que habían comprado laca que no era Nelly y la suya no pegaba nada... Pero se nos olvidó bajarla después de usarla :sweaty_smile:

Estoy gestionando su devolución.

**Comment by Siotma** [comment]
Sin problema, David, lo importante es saber dónde está. Mi preocupación era que alguien la hubiera mangado pero ya veo que no :)

La laca ha sido devuelta, la he dejado junto a las impresoras.

Issue cerrada en tiempo récord.
