### ISSUE TITLE
Diseñar a medida e imprimir soportes de motores de Blacky

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/impresoras-asrob#21]
Una de las piezas que sujetan los motores de Blacky para evitar que vibren ha desaparecido. Creo que el diseño era de @Siotma

**Comment by Siotma** [comment]
En efecto, el diseño inicial es mío, ya que yo diseñe [estas piezas](https://github.com/Siotma/developrints/tree/master/Soporte%20motor%20Z) para mi impresora.

Sin embargo, no ha desaparecido nada, puesto que únicamente se imprimió una pieza, no dos.

El motivo de que solo se imprimiera una es que por aquel entonces, Hija Resurrection tenía el problema de pasos por mm ( #4 ), y de hecho las medidas de la pieza que hay son erróneas, y la pieza es más grande de lo debido.

Por otra parte, para imprimir la pieza para Blacky, hay que escalarla en Z, ya que los motores están mucho más cerca de la mesa que en el caso de mi impresora.

Propongo como ejercicio, rediseñar la pieza en FreeCAD ahora que sabemos :P y hacerla a medida de Blacky.

**Comment by jorgercobo** [comment]
Pues creo que está cambiada de sitio y al verla vibrar me he hecho un lio 😅

**Comment by Siotma** [comment]
Hoy, he roto el único soporte que había, ya que ha demostrado ser demasiado grueso y desequilibrar a Blacky, actualizo la tarea a "Diseñar a medida e imprimir soportes de motores de Blacky".

**Comment by Siotma** [comment]
Hoy hemos medido la distancia entre los motores y la mesa: 2mm aproximadamente, y he diseñado esta pieza: [Soporte motor Z Blacky.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/1028841/Soporte.motor.Z.Blacky.zip)

Hemos impreso uno con Hija Resurrection (para que sea negro y haga juego con el resto de las piezas de Blacky):

![soporte motor z blacky](https://cloud.githubusercontent.com/assets/6171234/26449022/606caffe-4150-11e7-9e3f-ca912ec17405.jpg)

Quedaría por imprimir otro idéntico. El archivo está en el ordenador de Hija Resurrection dentro de la carpeta Printer One, que está en el Escritorio:

![soporte motor z blacky ubicacion](https://cloud.githubusercontent.com/assets/6171234/26449061/8e44e702-4150-11e7-9940-f6917078c763.jpg)

Planeado para la siguiente sesión.

**Comment by Siotma** [comment]
Hoy, se ha impreso la base que faltaba: https://github.com/asrob-uc3m/impresoras-asrob/issues/12#issuecomment-306869765 

![soporte motor z blacky colocado](https://user-images.githubusercontent.com/6171234/26892478-be80e16a-4bb8-11e7-89e9-afe59d24d3a6.jpg)
