### ISSUE TITLE
Thermal runaway

### ISSUE THREAD

**Issue by pamarinp** [asrob-uc3m/impresoras-asrob#23]
Mientras imprimia 4 ruedas del protobot se ha detenido la impresión a los 20 minutos aproximadamente en la segunda da capa. El fallo es debido a una caída de temperatura por parte del termistor del extrusor. 
![img-20170518-wa0021](https://cloud.githubusercontent.com/assets/9695183/26217209/de3b9e80-3c06-11e7-821a-e05f66b7f3fa.jpeg)
![img-20170518-wa0019](https://cloud.githubusercontent.com/assets/9695183/26217208/de3b9c14-3c06-11e7-9791-a5b4b28ee887.jpeg)
![img-20170518-wa0017](https://cloud.githubusercontent.com/assets/9695183/26217210/de3e0986-3c06-11e7-97af-93c6013e72d9.jpeg)

He intentado continuar la impresión sin éxito puesto que el programa se queda en calentando la impresión y no responder de ni a control manual de los motores.

**Comment by Siotma** [comment]
Es un fallo que ha sido recurrente últimamente, ya que detecta variaciones grandes en las temperaturas y realiza una parada de emergencia para evitar que la impresora se autodestruya.

Aunque las últimas veces se había activado la protección de forma demasiado rigurosa ( #20 , https://github.com/asrob-uc3m/impresoras-asrob/issues/12#issuecomment-298057269 , https://github.com/asrob-uc3m/impresoras-asrob/issues/12#issuecomment-298969157 ); en este caso yo creo que se ha activado correctamente, a la vista de la gráfica de temperatura 🎉 

Sospecho que el Kapton que sujeta el termistor del extrusor está cada vez más deteriorado y el termistor está empezando a moverse durante la impresión.

Recomiendo que se cambie el Kapton del extrusor por un trozo nuevo.

Gracias por la documentación @pamarinp , nos ponemos con ello!

**Comment by Siotma** [comment]
Hoy hemos repuesto el Kapton en Hija Resurrection. He traído un poco del mío mientras se adquiere el de la asociación ( https://github.com/asrob-uc3m/actas/issues/62 ).

Ha quedado muy bien, afianza el termistor firmemente y sobre todo ¡¡No se chamusca!! XD

Adjunto imagen que muestra el estado en que se encontraba el extrusor:
![kapton malo hija resurrection](https://cloud.githubusercontent.com/assets/6171234/26448811/6e4eca18-414f-11e7-825d-f638f2a3c4bd.jpg)

Y ahora:
![kapton bueno hija resurrection](https://cloud.githubusercontent.com/assets/6171234/26448814/736e0e50-414f-11e7-928e-7bfe84d6d447.jpg)

La impresora ha estado imprimiendo dos horas seguidas sin errores, por lo que damos por validado el arreglo:

![impresion hija resurrection2](https://cloud.githubusercontent.com/assets/6171234/26448891/d5283544-414f-11e7-824d-47d45b341a68.jpg)
