### ISSUE TITLE
Soldar y colocar los ventiladores de la electrónica de Blacky

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#24]
La posición más óptima parece ser crimpando directamente a los cables de la fuente de alimentación correspondientes al conector de 5A ( [ver imagen](http://www.reprap.org/wiki/File:Arduinomega1-4connectors.png) )

Se deben buscar los conectores necesarios y proceder a su montaje.

**Comment by Siotma** [comment]
Dado que se cambió la fuente de alimentación ( #28 ), ahora debería ser mucho más fácil añadir los ventiladores utilizando una nueva línea de 12V y conectores apropiados.

**Comment by GioSunrider** [comment]
Se han soldado y colocado los ventiladores a la electrónica.  Se han soldado a la fuente en paralelo en un extremo de un canal de 12V. Adjunto fotos de la colocación.

![photo6032812494365502062](https://user-images.githubusercontent.com/10605193/32175377-1046ec04-bd85-11e7-9974-59cbaf287826.jpg)

![photo6032812494365502063](https://user-images.githubusercontent.com/10605193/32175378-105dc79e-bd85-11e7-9797-d9da4dae7029.jpg)

**Comment by Siotma** [comment]
¿Qué ha pasado en esta Issue? Aparece un tal @ghost 😕  y se ha perdido el comentario de @GioSunrider... 

Jorge, has eliminado tu usuario?

No entiendo nada...

**Comment by GioSunrider** [comment]
Mi usuario se ha como bloqueado y no se por que, voy a ver.

**Comment by Siotma** [comment]
Ya me aparece todo bien. Habrá sido un fallo de GitHub.

Lo has hecho fantástico: Asignar, cerrar y mover la ficha a Done.

**Comment by GioSunrider** [comment]
Gracias 😊😊
