### ISSUE TITLE
Error de envío de datos por puerto USB

### ISSUE THREAD

**Issue by pamarinp** [asrob-uc3m/impresoras-asrob#27]
Esta vez ha sido un error de conexión. A mitad de la impresión ha saltado el siguiente error.
![img_20170607_195552143](https://user-images.githubusercontent.com/9695183/26896794-6d85a328-4bc6-11e7-860d-0560893fc233.jpg)

**Comment by Siotma** [comment]
Los errores de conexión son mucho más comunes al imprimir desde el PC. Imprimiendo desde tarjeta SD se suelen minimizar.

También creo que sería interesante actualizar la versión de Repetier a la última versión ya que creo que tienen mejoras para evitar estos errores.

**Comment by David-Estevez** [comment]
En el caso de mi impresora de casa, los errores de conexión se resolvieron al usar cables USB con ferrita. No me he fijado en si los cables de las impresoras de la nave tienen o no ferrita, pero si no la tienen debería mejorar la conexión al cambiarlos.

**Comment by Siotma** [comment]
Este error se volvió a manifestar en la [última reunión de Printer One](http://asrob.uc3m.es/index.php/Printer_One:_A_Clone_Wars_Story:_Cuaderno_de_Bitacora#15_de_septiembre_de_2017). Por tanto, urge repararlo.

**Comment by Siotma** [comment]
La actualización en el software del ordenador de Hija Resurrection ( #3 ) debería haber solucionado este problema.
