### ISSUE TITLE
LCD para las Impresoras

### ISSUE THREAD

**Issue by d-marcos-m** [asrob-uc3m/impresoras-asrob#40]
En la última reunión, decidimos ponerle una pantalla de BQ que teníamos en el armario. Se editó el Configuration.h (pendiente subir el actualizado) y se subió el nuevo firmware. 

- [x] Actualizar el Configuration.h en GitHub.

Todo funcionó bien, pero a la hora de apagar el ordenador que controla a Blacky, la pantalla sigue encendida, ya que se alimenta a través del USB de la torre del ordenador. Trasteé un poco en la BIOS, pero no conseguí hacer que los puertos USB no reciban alimentación una vez el ordenador está apagado. Si alguien tiene idea de como evitar esto, que lo diga. La pantalla se queda encendida si no solucionamos eso, por lo que ahora mismo está desconectada y guardada en la caja blanca de Printer One. 

- [x] Configurar el apagado de los USB de los PC.

- [x] LCD en Blacky
- [x] LCD en Hija
- [x] LCD en Dedalo

**Comment by GioSunrider** [comment]
Para la proxima sesion imprimir el recubrimiento del LCD que ira en Hija Resurrection, en [este enlace](https://www.thingiverse.com/thing:638833/#files) se pueden encontrar.

**Comment by GioSunrider** [comment]
Se imprimió y se coloco el LCD de Blacky. Adjunto fotos del soporte, que a su vez queda añadido a la carpeta de `parts` de Blacky, y del LCD instalado.
Admas se probo su funcionamiento y no da ningun problema.

![photo5881893635711150921](https://user-images.githubusercontent.com/10605193/34041665-5c4d4214-e199-11e7-9b5b-fc5a61a7de2e.jpg)

![photo5881893635711150922](https://user-images.githubusercontent.com/10605193/34041667-5c681526-e199-11e7-92ec-b4506470e10e.jpg)

![photo5881893635711150923](https://user-images.githubusercontent.com/10605193/34041669-5c82544a-e199-11e7-9f0f-b01f470ef768.jpg)

**Comment by d-marcos-m** [comment]
A la hora de intentar solucionar el tema de la alimentación de la placa cuando el ordenador está apagado, decidimos optar por modificar los cables de las impresoras para que fuesen data-only.
Para hacer esto, no hay más que abrir el cable, y sabiendo que de los 4 cables que tiene dentro (blanco, negro, verde y rojo?), el rojo es VCC, procedimos a cortar el rojo, cubrir los 2 trozos que quedan tras cortar con termoretractil, y cerrar el cable con cinta. 
Tras hacer una prueba y ver que funcionaba, lo hicimos para las 3 impresoras. 
Sin embargo, en la impresora hija no funcionó, imaginamos que por la placa, así que la propuesta fue que si no conseguimos que funcione, cambiar la placa por la nueva de BQ que hay en el armario, ya que tenemos una pantalla que queríamos poner en hija. No sin antes probar que la pantalla efectivamente se queda encendida al apagar el ordenador.

**Comment by Siotma** [comment]
Respecto a la colocación de la pantalla sobre el marco de la impresora, yo puedo aportar que en mi experiencia **es un mal sitio**: si se interactúa con la pantalla durante la impresión es muy fácil hacer oscilar el marco de metacrilato, y ello puede hacer que el extrusor se mueva (suba o baje), dejando imperfecciones en la pieza. Este tipo de montajes son más apropiados para estructuras más robustas como la de Hija Resurrection o Dédalo. El problema de oscilación del marco es inherente al modelo de impresora, yo hace poco puse [estas piezas](https://www.thingiverse.com/thing:603953) a la mía para afianzar el marco.

Respecto al problema de alimentación de la RAMPS de Hija Resurrection por USB, habría que hacer pruebas pero a mi me pasó algo muy parecido y el problema era de la MEGA. No funcionaba correctamente el pin de Vin y por tanto los 12V no la encendían. Creo que antes de cambiar la placa deberíamos revisar con el multímetro tensiones en algunos puntos: http://www.reprap.org/wiki/RAMPS_1.4/es#D1.2C_D2_-_Diodos

**Comment by Siotma** [comment]
En la reunión del día 21, pusimos a Blacky a imprimir desde la SD, obteniendo muy buenos resultados:

<img align="center" height="300" src="https://user-images.githubusercontent.com/6171234/34325924-2d3311d4-e8a1-11e7-8e79-23c8f6754716.jpg"></img>

Ahora mismo, Blacky es totalmente funcional mediante la LCD, por tanto, urge, actualizar el [manual de usuario](https://github.com/asrob-uc3m/impresoras-user-manual-i3), ver la issue correpondiente: https://github.com/asrob-uc3m/impresoras-user-manual-i3/issues/4

**Comment by d-marcos-m** [comment]
En la sesión del pasado jueves instalamos también la pantalla de Hija, en este caso una full graphics. Actualizamos el firmware y los nuevos archivos de configuración quedaron subidos al repo. El próximo día añado fotos :D

**Comment by d-marcos-m** [comment]
Añado foto de Hija con pantalla :) (Felices fiestas!)

![indice](https://user-images.githubusercontent.com/14359236/34420973-e262e610-ec0c-11e7-8acb-f33b8a154f8a.jpg)

**Comment by Siotma** [comment]
Alguna noticia del [LCD de Dédalo](https://github.com/asrob-uc3m/impresoras-asrob/issues/31#issuecomment-344561347) @David-Estevez ?

**Comment by David-Estevez** [comment]
Pues algo me dice que la traerán los Reyes Magos....

**Comment by David-Estevez** [comment]
Ya tenéis vuestro regalo de Reyes en el armario :wink: 

![image](https://user-images.githubusercontent.com/1451819/34666889-cbf96c0c-f466-11e7-80c5-f290951b9cb7.png)

**Comment by Siotma** [comment]
> Ya tenéis vuestro regalo de Reyes en el armario 😉

Muchas gracias!

Hemos venido entusiasmados a la reunión para poder probarla, pero nos hemos dado cuenta enseguida de que no vamos a poder usarla con la Sanguinololu. En realidad, no sabemos si la pantalla es compatible o no, pero el adaptador, es decir, la pieza pequeña blanca señalada en la siguiente imagen, es para RAMPS. Además, en la pegatina del paquete de la pantalla también se indica que es una kit para RAMPS.

![wrong_dedalo_screen](https://user-images.githubusercontent.com/6171234/34729770-e13bcdf6-f55d-11e7-8cb5-432dd81b2780.jpg)

La dejamos donde estaba, no la hemos llegado a abrir. Seguramente puedas poner una reclamación al vendedor para que te envíe el adaptador correcto. Algo como esto:

![geeetech_img_6853_2](https://user-images.githubusercontent.com/6171234/34729890-2ad2c636-f55e-11e7-8b70-769767fbb1ac.jpg)

Con un adaptador adecuado, tal vez esta pantalla funcione. Nos vas contando @David-Estevez .

**Comment by David-Estevez** [comment]
Disputa abierta con el vendedor, le he pedido que me envíe el adaptador correcto o que me devuelva 3€ para que le pueda comprar otro a otro vendedor. Os mantengo informados de lo que me vaya diciendo.

**Comment by Siotma** [comment]
En la última reunión, se imprimieron [estas piezas](https://www.thingiverse.com/thing:638833/#files) para hacerle una carcasa a la pantalla de Hija Resurrection.

![hijaresurrection_new_screen](https://user-images.githubusercontent.com/6171234/34823408-879f0240-f6ca-11e7-9725-7ce3f59c65af.jpg)

Además, se practicó un agujero en la parte inferior de la carcasa para dejar la pantalla atornillada sobre la impresora:

![hijaresurrection_new_screen_fixed](https://user-images.githubusercontent.com/6171234/34823423-942c4342-f6ca-11e7-96c7-bc555989955d.jpg)

**Comment by David-Estevez** [comment]
El vendedor aceptó el reembolsarme 3€, con los que he comprado otro adaptador distinto en Aliexpress. En lo que llega os dejo la placa otra vez en el armario, por si se la queréis poner temporalmente a otra impresora o algo.

**Comment by GioSunrider** [comment]
Issue que queda en stand-by, debido a que la pobre placa de dedalo cuando se le conecto la pantalla, el adaptador tenia los pines desalineados e hizo una mala conexion y salio ardiendo como se refleja en [#46](https://github.com/asrob-uc3m/impresoras-asrob/issues/46). Cuando evaluemos el problema se vera que hacer en esta issue.

**Comment by GioSunrider** [comment]
Hoy hemos montado la placa de Dédalo (#48) y hemos conectado la pantalla que llevaba 2 meses en el armario. ~10 asrobcoins para @dmarcosm

**Comment by Siotma** [comment]
Piezas LCD Hija actualizadas via 0363e391158485261eb205cfc239e86b738a5702
