### ISSUE TITLE
Extrusor de Blacky atascado

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/impresoras-asrob#47]
Esta tarde durante la reunión de RoboFactory hemos intentado imprimir unas piezas en ABS negro con Blacky.

La impresora no extruía nada, así que procedimos a intentar extruir a mano sin éxito. Al intentar extraer el filamento no salía, y lo hemos acabado partiendo.

**Comment by GioSunrider** [comment]
Tiene, tanto extrusor como el barrel recién puestos, igual es el filamento ese negro que es muy mierda y le usamos como señuelo. Si vuelve a pasar, en el armario hay agujas para desatascar (son las de acupuntura) en el armario que nos trajo Diego. Aún así el próximo día le echaremos un vistazo a ver cuál es la causa.

**Comment by David-Estevez** [comment]
Como se partió el filamento y había poco margen de maniobras preferimos no seguir tocando nada para no empeorar la situación. Pero sí que es posible que fuese por usar el plástico negro ese malucho.

**Comment by GioSunrider** [comment]
Se ha limpiado el atasco. Este se debió a la mala, malisima calidad del teflón en el barrel. Solo quedan hacer las pruebas de impresión tras la limpieza.

**Comment by d-marcos-m** [comment]
Añadir que se ha hecho una pequeña modificación en el barrel para poder usarlo en el extrusor que actualmente usa Blacky, la cual arregla el problema por el cual se producía el atasco.
El barrel que se utiliza en este tipo de extrusor es tal que así: 

![barrel-ptfe-m6-con-teflon-para-hotend-e3d-impresora-3d-d_nq_np_852421-mla20755236476_062016-f](https://user-images.githubusercontent.com/14359236/37179851-66fec384-2327-11e8-87ff-464002df43c1.jpg)

Este barrel tiene en la parte de arriba un trozo liso, sin rosca. Al tener los barrels que habíamos probado rosca hasta el final, no llegaba a entrar del todo, y quedaba un hueco en el cual el plastico se expandía, y, por tanto, se atascaba. Para solucionarlo hemos lijado la rosca sobrante para que entrase del todo. De esta forma Blacky quedaría (a falta de pruebas) operativa con PLA. La otra solucion era dejarle el barrel sin teflon que ya tenia ese trozo liso, pero solo serviría para usarla cn ABS. 
No hay fotos, el próximo día :)

**Comment by David-Estevez** [comment]
Ahhh, así que para eso era la Dremel... :joy: :joy:

**Comment by d-marcos-m** [comment]
En la sesión de ayer pusimos a Blacky a imprimir una carcasa para la Raspberry Pi y lo hizo de maravilla, así que damos por solucionado este problema :+1: 

![photo5861742654180666275](https://user-images.githubusercontent.com/14359236/37544972-36e28d8e-2967-11e8-9fc1-2d85600b6d47.jpg)

**Comment by GioSunrider** [comment]
Cabe destacar, que hoy me ha costado bastante colocar el filamento, esto se debe a la modificacion del barrel, ya que se nota donde choca por la cantidad de filamento introducida. Si el filamento no entra recto cuesta bastante de colocar, a pesar de todo, Blacky ha impreso correctamente como se puede demostrar en la siguiente foto.

![photo5872758167258115951](https://user-images.githubusercontent.com/10605193/37626863-04ad2226-2bd2-11e8-8d50-42b77e57c370.jpg)

**Comment by Siotma** [comment]
Es importante que al introducir el filamento, la punta de este no sea demasiado ancha. Esto ocurre habitualmente cuando el filamento se saca del extrusor para guardar. La punta se ha ensanchado como producto del calor y al intentar volver a ponerlo le cuesta entrar. La solución de baja tecnología para esto es romper la punta y tirarla.

Además, como tú dices, el filamento debe estar recto para entrar más fácilmente. Para ello se pueden enderezar fácilmente con los dedos.

**Comment by GioSunrider** [comment]
Creeme que hice todo, pero bueno, quiero que quede reflejado que da problemas aun haciendo todo.
