### ISSUE TITLE
HIJA RESURRECTION Impresora atascada

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/impresoras-asrob#5]
Nota: Issue puesta hoy por @David-Estevez migrada desde asrob-uc3m/impresoras-maintenance-manual-i3#3

La  impresora que no es negra (la Steel) está atascada.

Cuando llegamos el racor de la entrada estaba quitado.

Al intentar colocar el nuevo filamento, nos dimos cuenta de que ya había uno colocado, pero cortado a una altura justo por debajo de los engranajes. Calentando el hotend a 200ºC e intentando sacar / meter el trozo de filamento que hay dentro, el filamento no se mueve en absoluto.

Lo que viene siendo un atasco total.

**Comment by jorgercobo** [comment]
Impresora desatascada, queda pendiente comprobar si funciona correctamente, reordenar el cableado y de algún modo enganchar la tapa del ventilador del extrusor que está suelta en la parte superior. Abro issue para arreglar el resto de problemas.
