### ISSUE TITLE
Quedada de impresoras: trae la tuya! 

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#55]
Muchos de los miembros de ASROB tenemos impresoras en propiedad. Todos nosotros queremos nuestras impresoras como a la que más, y las tenemos bien cuidadas y puestas a punto.

Creo que sería muy interesante hacer una quedada en la Universidad en la que cada uno nos llevemos nuestra impresora y las pongamos todas a imprimir:
- Primero, porque **molaría muchísimo**. Calculo que podemos llegar a juntar más de 10 impresoras fácilmente, imagina todas imprimiendo a la vez.
- Segundo, porque es una oportunidad para **aprender unos de otros**. Podremos comprobar qué configuración electrónica, mecánica y de firmware utiliza cada uno, intercambiar impresiones sobre dificultades encontradas durante su uso o calibración y comprobar cómo lo ha resuelto cada uno.
- Tercero, porque con tantas impresoras juntas se pueden **hacer grandes cosas**. Podríamos plantear un reto de impresión, en el que entre todos imprimamos, por trozos, algo grandioso, como por ejemplo, [la mascota de ASROB](https://github.com/asrob-uc3m/recursos-digitales/tree/develop/logos/3d).

Para participar, solo haría falta que cada asistente aporte:
- Al menos, una impresora 3D, preferiblemente dotada de tarjeta SD para no tener que andar con PCs y aprovechar mejor el espacio.
- Filamento y soporte (se puede llegar a un acuerdo a priori sobre qué colores usar).
- Laca y utensilios de limpieza de base y de despegado de piezas.

Dadas las características de la actividad, creo que debería durar al menos "toda una mañana" o "toda una tarde". Molaría poder hacerlo un sábado pero yo no tengo potestad para abrir la universidad en sábado, así que no lo propongo.

Dejo aquí un doodle para que cada cual indique su preferencia de día y hora: https://doodle.com/poll/x4w4piwathbssqwd

**Comment by GioSunrider** [comment]
I'M IN!

**Comment by David-Estevez** [comment]
Igual es una idea de olla, pero si lo movemos con gente de fuera (Clone Wars, etc) igual podríamos montar un evento guapo, guapo. 

* Pros:
    * Conocer a un montón de gente guay
    * Igual hasta dan créditos por una Printer Party :joy: 
* Contras:
   * Limitación de espacio (aunque se podrían buscar alternativas)
   * Organización más costosa

Bueno, yo lo propongo como locura y a ver qué pasa...

**Comment by d-marcos-m** [comment]
Me gusta la idea de @David-Estevez ,

Quizá lo más problemático como dices sería encontrar el espacio (sin salir de la uni), pero todo es ponerse

**Comment by GioSunrider** [comment]
Me gusta también la idea, de hecho yo lo que propuse fue pedir permiso a la uni para organizar este evento en un aula grande y hacer eso, una Printer Party. Igual nos metemos en un jardín, pero molaria.

**Comment by David-Estevez** [comment]
También se puede hablar con gente para intentar organizarlo en otro sitio con más espacio. Así sin pensarlo mucho se me ocurre el Medialab Prado, por ejemplo.

**Comment by d-marcos-m** [comment]
Por listar otros sitios que estarían bien, se me ocurren el Open space de leganes (50 personas?), La Nave en villaverde (lanavemadrid.com)

**Comment by GioSunrider** [comment]
Pero para eso habría ya que poner pasta verdad?

**Comment by d-marcos-m** [comment]
Sería cuestión de mandar mails y ver qué necesitamos.

**Comment by David-Estevez** [comment]
Si os mola la idea puedo hablar con la gente del MakeSpace Madrid a ver si se animan a ayudarnos a organizarlo.

**Comment by d-marcos-m** [comment]
A mi me parece buena idea, así que diría que adelante con ello.

**Comment by GioSunrider** [comment]
A mi también. Así que podemos mirarlo.

**Comment by JorFru** [comment]
Si la organización de el resto de eventos que tengo me lo permiten, estoy
dentro chavales.
Me refiero al hackatón ASROB-UC3Music

**Comment by Siotma** [comment]
Por una parte, me encantaría poder aspirar a un evento tan chulo como el que proponéis. El problema que le veo es que luego igual la asistencia es un fracaso... 

La finalidad de esta issue no es tan ambiciosa y creo que podría ser un buen punto de partida organizar algo pequeño a nivel de ASROB, buscando fomentar la participación interna, para en el futuro organizar algo más grande si nos vemos con ganas.

Dado que actualmente en el doodle solamente hay apuntadas 3 personas, no sé si es buena idea querer volar tan alto cuando aún no hemos empezado a caminar.

**Comment by d-marcos-m** [comment]
Si organizaciones más grandes como MakeSpace Madrid nos ayudan yo creo que la asistencia no tendría por qué ser un fracaso, no?

**Comment by David-Estevez** [comment]
Yo he mandado un mail por si acaso y os voy diciéndo qué les parece la idea.

**Comment by GioSunrider** [comment]
Como va a quedar la cosa al final?

**Comment by Siotma** [comment]
De momento somos 3 apuntados! :sweat_smile:

**Comment by JorFru** [comment]
Sí, y uno es un tío random que no conocemos de nada.
https://thesongswelove.files.wordpress.com/2014/11/giorgio.jpg?w=625&h=390&crop=1

**Comment by Siotma** [comment]
Me parece que de momento esta idea va a tener que replantearse, porque la participación no ha tenido mucho éxito.

**Comment by jgvictores** [comment]
La idea mola... A ver si conseguimos a más gente para el día 12-13. :- )

Repito link: https://doodle.com/poll/x4w4piwathbssqwd

cc: @diegotrap ??
cc: ((@asrob-uc3m/impresoras inserten vuestros contactos aquí))

**Comment by jgagom** [comment]
Me apunto a llevar la mía si es el 12! Aunque habrá 3h en las que tendré que estar en la nave con el autómata porque tengo clase. Tiene muy buena pinta el evento, a ver si se anima más gente!

**Comment by Siotma** [comment]
Parece que podemos todos el jueves por la tarde, conque voy a establecer ese día y lo rulamos por los grupos para ver si más gente se anima! :wink:

**Comment by Siotma** [comment]
Fijado el jueves día 12 de abril de 15:00 a 21:00 para la primera quedada de impresoras ASROB.

Comentad vuestras ideas sobre qué imprimir durante tan maravilloso día!

**Comment by Siotma** [comment]
Corrección: 

Fijado el jueves día **12 de abril de 15:00 a 21:00** para la primera quedada de impresoras ASROB.

Comentad vuestras ideas sobre qué imprimir durante tan maravilloso día!

**Comment by Siotma** [comment]
Yo no podré llegar hasta las 18:00 o algo más tarde, pero en cuanto llegue me pongo al día!

**Comment by Siotma** [comment]
Finalmente el día llegó, y **conseguimos juntar 8 impresoras**: las 4 de ASROB más otras 4, propiedad de:

- @GioSunrider 
- @JorFru 
- @wenflehecanario
- @Siotma 

Durante la tarde compartimos distintas experiencias de montaje y uso de las impresoras, con mención especial a la enorme variedad de filamentos que trajo @JorFru .

Además, este encuentro atrajo la atención de otros muchos miembros de la asociación, superando los 15 asistentes a lo largo de la tarde, y fomentó su interés por las impresoras, dándoles la oportunidad de conocer el mundillo más de cerca. Por ello, se dan por cumplidos los objetivos principales de este encuentro.

Como pega, finalmente no se consiguió organizar un reto de impresión, por lo que cada asistente imprimió lo que consideró más oportuno. Para futuras ocasiones y para darle un mayor interés, este aspecto debe ser preparado con antelación.

Una foto para la posteridad:

![12_04_2018_printer_meeting](https://user-images.githubusercontent.com/6171234/38780016-ef8277d4-40d0-11e8-9c5f-9542615f1121.jpg)

Hasta la próxima!
