### ISSUE TITLE
Montaje de Geonosis

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#57]
Esta issue es para documentar y gestionar el proceso de montaje de la nueva impresora.

Para cerrar esta issue al menos:

- [x] Se construirá la impresora por completo, documentando gráficamente el proceso y el resultado.
- [x] Colocar la electrónica y los cables con doble ración de epicness.
- [x] Se reflejarán los problemas surgidos durante el montaje y se aportarán ideas para resolverlos.
- [x] Se realizará la primera impresión.
- [x] Se documentarán los perfiles de impresión y los archivos de configuración en este repositorio.

El último día estuvimos siguiendo [este manual](http://nathan.vertile.com/blog/2018/01/11/tronxy-x5s-build-guide/) de montaje y también fue útil [este otro](http://diy3dtech.com/gearbest-tronxy-x5s-3d-printer-manual/).

![05_04_2018_tronxy_building](https://user-images.githubusercontent.com/6171234/38453721-9831fbd4-3a5a-11e8-8011-8e731efe436b.jpg)

Manos a la obra!

**Comment by d-marcos-m** [comment]
La impresora ha quedado montada entre el pasado jueves y la mañana de hoy. Hemos hecho la primera impresión (un calicat!) y no ha salido para nada mal :) Dejo algunas fotos del proceso y de dicha impresión:

![photo5936233450270993099](https://user-images.githubusercontent.com/14359236/38510355-1e7b46f2-3c25-11e8-8f5a-bc0e58788e33.jpg)

![photo5936233450270993107](https://user-images.githubusercontent.com/14359236/38510361-23df6ef2-3c25-11e8-8a95-4562f33617ce.jpg)

![photo5936233450270993143](https://user-images.githubusercontent.com/14359236/38510364-2825d47e-3c25-11e8-8f52-b8c570778661.jpg)

Además, @JorFru ha hecho un cable management de los suyos :D 
## **Antes:**
![photo5936233450270993108 1](https://user-images.githubusercontent.com/14359236/38510418-55b62c68-3c25-11e8-93a8-69ecaa04a408.jpg)
## **Después:**
![photo5937036476011358153](https://user-images.githubusercontent.com/14359236/38510426-5bc5ed0a-3c25-11e8-80c6-a1f7b37c16dd.jpg)

**Comment by d-marcos-m** [comment]
**Problemas encontrados durante el montaje:**

- Uno de los perfiles no tenía la rosca bien hecha y los tornillos no apretaban. Tras intentar poner arandelas para que apretase sin éxito, optamos por darle la vuelta y usar el lado sin forma (?), ya que no era imprescindible en ese caso usarla con la orientación "correcta"
- Según comenta @JorFru, el cable de uno de los motores de Z no llega bien a la placa al hacer el buen cable management, le faltan unos 10cm, por lo que habría que hacer un empalme para que quede bien del todo. 
- La cadeneta horizontal que va por encima de la cama estaba algo defectuosa. Uno de los extremos no enganchaba bien con el anterior eslabón y por lo tanto quedaba un poco caída (con el tiempo podría llegar a caer más y chocar con la cama supongo). Hemos optado por ponerle una brida y ha quedado arreglado, al menos de forma temporal.
- La pieza donde se atornilla la cadeneta del eje Z tenía los agujeros muy pequeños y al principio no entraban los tornillos. Simplemente los hemos agrandado un poco con un destornillador y el problema ha quedado resuelto. 

**Otras observaciones:**
Falta por poner la tapa/ventilador de la placa. Apoyo una idea que ha dado @JorFru, y es que es una pena tapar por completo una placa que ha quedado tan bien. La sugerencia es imprimir un soporte para el ventilador que deje más a la vista la placa (como el que tiene Hija, por ejemplo). También cabe la posibilidad de cortar el acrílico que ya tenemos :) 
Por último, la cama nos ha parecido un poco cutre. De primeras, al calibrar la impresora por primera vez se ve que nos hemos acercado demasiado y ha quedado una pequeña marca, que no es muy notable pero ahí está. Hemos hablado de que quizá no se
ría mala idea cambiar la base de acrílico por un cristal de 330x330mm, que no sería muy caro. 
En el tutorial de montaje que hemos utilizado enlazan a un Marlin modificado para varios problemas habituales de esta impresora (sobre todo cosas de la pantalla y los pasos/mm). Lo más probable es que optemos por usar esa versión (1.1.6) modificada e ir cambiando cosas desde ahí.

**Comment by Siotma** [comment]
El resultado es fantástico! 

Creo que puedo ayudar en el tema del espejo: [en IKEA los tienen de 30x30](https://www.ikea.com/es/es/catalog/products/39151700/) :+1:

**Comment by d-marcos-m** [comment]
La cama realmente es de 33x33, creo que sería mejor comprar un cristal, y aprovechar toda la superficie

**Comment by Siotma** [comment]
Estoy de acuerdo con eso :rofl: :sweat_smile: 

![lol](https://user-images.githubusercontent.com/6171234/38515115-91aed4aa-3c33-11e8-8cfc-c405b8fd69c7.jpg)

**Comment by d-marcos-m** [comment]
> Estoy de acuerdo con eso rofl sweat_smile

Realmente por eso mismo propuse hacer la superficie magnética, porque aprovechas la superficie al 100%, sin pinzas ni nada. 
También está la ópción de las típicas piezas impresas que sujetan el cristal por las esquinas.

**Comment by GioSunrider** [comment]
Creo que si ponemos cristal la plancha magnetica va a servir de poco por el peso del cristal. Mejor imprimiria las piezas de las esquinas.

**Comment by d-marcos-m** [comment]
> Creo que si ponemos cristal la plancha magnetica va a servir de poco por el peso del cristal. Mejor imprimiria las piezas de las esquinas.

No te sigo. Qué tiene que ver el peso del cristal?

**Comment by GioSunrider** [comment]
que pude haber movimientos faciles de que se vaya mientras imprime, como en algun momento haya un minimo error y roce la punta puede desplazar con mayor facilidad el cristal, a eso me refiero.

**Comment by d-marcos-m** [comment]
A mi me gusta también más la solución de las piezas impresas, que conste (por aquello de hacerlo nosotros), pero el cristal con el iman no se mueve con un toquecito.

**Comment by GioSunrider** [comment]
Si has hecho pruebas con cristal votare a favor, pero creo que con la lamina de PEI hay muchas diferencias que no se pueden aplicar a un cristal.

**Comment by David-Estevez** [comment]
Le pongas lo que le pongas no se va a mover porque la base sólo se desplaza en Z

**Comment by GioSunrider** [comment]
Por moverse me refiero, que el extrusor choca con una pieza impresa, y esta al hacer la fuerza la cama se acabe desplazando, pero oye, si lo veis con fuerza adelante jajajajaja a mi me gustan mas las pinzas de extremos.

**Comment by David-Estevez** [comment]
Los imanes de neodimio tienen mucha fuerza los muy jodíos, no creo que se mueva con un simple toque del extrusor.

Por ejemplo, la base de la M-Prime que tengo en casa está sujeta con imanes y no he tenido todavía ningún problema de que se haya movido (y eso que en la M-Prime la base sí que se mueve al imprimir).

**Comment by GioSunrider** [comment]
Hombre en cuanto a precio igual unas planchas de neodimio se nos va la olla ajajajajaja
Y en cuanto a eso como queráis, si queréis imanes adelante, no me opondré xF

**Comment by David-Estevez** [comment]
Planchas no, con poner uno en cada esquina es suficiente. Un plancha yo creo que no la despegas ni de coña (igual tú sí, pero por tu fuerza sobrehumana :sweat_smile: ).

**Comment by GioSunrider** [comment]
Jajajaajajaja es que creo que @daavm se refería por imanes a planchas que es lo que trajo un día, pero si, igual poniendo imanes en las direcciones de las camas sale un buen resultado.

**Comment by d-marcos-m** [comment]
Yo hablaba de planchas de estas flexibles, pero lo de los imanes no es mala idea :+1:

**Comment by d-marcos-m** [comment]
El jueves llegué algo antes y actualicé el firmware por el tema de los thermal settings. Hizo una impresión de unos 40-50 minutos y no hubo thermal runaway, así que lo dejaría como está (mismos ajustes que Hija). En cuanto pueda subo los archivos :)

**Comment by Siotma** [comment]
@dmarcosm cierra esta issue como acordamos ayer.

**Comment by JorFru** [comment]
https://youtu.be/4DUhI9M5A28
