### ISSUE TITLE
Nombre para la TronXY

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#58]
Necesitamos bautizar nuestra impresora, ya que quedó pendiente de #51 .

De momento he recopilado las ideas que se han ido dando:

- TronXY (el más original).
- StarKiller (nombre del planeta que destruye mundos en Star Wars VII).
- DeathStar (la Estrella de la Muerte dos veces destruida).
- Geonosis (planeta donde se fabrican droides de combate en el que C3PO dice la famosa frase de "robots fabricando robots, qué obscenidad").
- Caliprinter (porque se parece a un cubo de calibración).
- Borg (Cubo Borg es el nombre de el transporte interestelar de los aliens Borg en la saga Star Trek).
- C-Borg (como Borg pero suena a ciborg).
- XY-Borg (como Borg, pero suena parecido a ciborg y además mola porque es una CoreXY).
- Mjölnir (Como el martillo de Thor Dios del trueno! Porque nadie la va a poder levantar más que los dignos de ello)

Se aceptan todo tipo de sugerencias y comentarios.

Propongo seguir el siguiente esquema:
- [x] Lluvia de ideas hasta el próximo domingo.
- [x] Votación.

**Comment by David-Estevez** [comment]
Caliprinter (porque se parece a un cubo de calibración)

**Comment by JorFru** [comment]
Sugiero el nombre "Borg"
Se que es un nombre feo, pero tiene su explicacion.
Cubo Borg es el nombre de el transporte interestelar de los aliens Borg en la saga Star Trek.

![borg](https://user-images.githubusercontent.com/11017088/38805449-1ee3337e-4176-11e8-9372-133fe85497de.png)

**Comment by GioSunrider** [comment]
Ya que te pones ponle C-Borg, que hasta si lo pronuncias parece un ciborg xD

**Comment by d-marcos-m** [comment]
"Borg" me convence bastante, aunque Geonosis me ha empezado a gustar bastante. Va a estar jodido elegir (y si compramos otra? 😁)

**Comment by JorFru** [comment]
C-Borg, definitivo

**Comment by Siotma** [comment]
XY-Borg?

Actualizo la lista..

**Comment by David-Estevez** [comment]
![image](https://user-images.githubusercontent.com/1451819/38832628-6de7e6b6-41c3-11e8-9d28-68334b16f583.png)

:joy: :joy: :joy:

**Comment by GioSunrider** [comment]
Y, Mjölnir!? Como el martillo de Thor Dios del trueno! Porque nadie la va a poder levantar más que los signos de ello jajajajaajajaj

**Comment by Siotma** [comment]
Hoy es el último día para aportar ideas, mañana abriré votación con los nombres que haya.

**Comment by Siotma** [comment]
Votación abierta hasta el próximo jueves en https://goo.gl/forms/p1yVrF4RrPuYFcl52

**Comment by Siotma** [comment]
Acabo de cerrar la votación. De 8 votantes, Geonosis ha sacado 4 votos, más que ninguna otra. Los resultados se pueden ver pulsando el enlace del form: https://goo.gl/forms/p1yVrF4RrPuYFcl52 .

TronXY: 3 votos.
StarKiller: 2 votos.
DeathStar: 1 voto.
**Geonosis: 4 votos.**
Caliprinter: 2 votos.
Borg: 1 voto.
C-Borg: 3 votos.
XY-Borg: 0 votos.
Mjölnir: 1 voto.
El que queráis, pesados: 1 voto.

![captura](https://user-images.githubusercontent.com/6171234/39319274-e830ea0c-4980-11e8-8ac5-bb623c39b686.JPG)

Adorad a Geonosis!
