### ISSUE TITLE
La MEGA de Blacky ha muerto

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#62]
Hay que comprar una nueva Arduino MEGA para Blacky, pues la que tenía ha muerto.

Se puede reutilizar https://github.com/asrob-uc3m/impresoras-asrob/issues/48#issuecomment-372278058 :

> Voy con las placas que he mirado. 
> [OPCION 1](https://www.amazon.es/Tarjeta-Microcontrolador-ATmega2560-ATmega16U2-Compatible/dp/B06Y3ZHPWC/ref=sr_1_3?ie=UTF8&qid=1520853461&sr=8-3&keywords=Arduino+mega&dpID=51w0PuG6wHL&preST=_SY300_QL70_&dpSrc=srch)
> [OPCION 2](https://www.amazon.es/XCSOURCE®-Atmega2560-16AU-Tarjeta-Versión-TE629/dp/B01N51Y3EJ/ref=sr_1_11?ie=UTF8&qid=1520853461&sr=8-11&keywords=Arduino+mega)
> [OPCION 3](https://www.amazon.es/SODIAL-desarrollo-ATMega16U2-Mega2560-Arduino/dp/B00PXOGG74/ref=sr_1_14?ie=UTF8&qid=1520853461&sr=8-14&keywords=Arduino+mega)
> Esto para las placas Mega Imitación, deberíamos valorar tiempos, por eso lo pongo por Amazon.

Adjunto foto:

![2018_04_26_blacky_freaduino_mega_burnt](https://user-images.githubusercontent.com/6171234/39320542-b9270c60-4984-11e8-87e6-4431dc193bb1.jpg)

**Comment by Siotma** [comment]
Alguno tiene Amazon Prime para conseguir la OPCION 1 con envío gratis?

**Comment by David-Estevez** [comment]
Independientemente de que se compre una placa nueva, crees que merece la pena reparar la placa quemada?

**Comment by Siotma** [comment]
Podría merecer la pena, pero no para ponerla en una impresora, sino más bien para tenerla para prototipar...

**Comment by David-Estevez** [comment]
Sí, mi idea era más bien tenerla "de repuesto" por si alguna vez hace falta echarle mano para lo que sea.

**Comment by d-marcos-m** [comment]
Quizá sería lógico comprobar primero con otra RAMPS (la de Hija, mismamente), que ningún otro componente se ha visto afectado, así si hay que comprar más cosas las compramos de una sola vez, no?

**Comment by GioSunrider** [comment]
>Alguno tiene Amazon Prime para conseguir la OPCION 1 con envío gratis?

Yo, y podria comprarla sin problemas. Pero la idea de @dmarcosm me parece muy adecuada.

**Comment by Siotma** [comment]
> si hay que comprar más cosas las compramos de una sola vez

Agrupar artículos en un mismo pedido es algo muy interesante para repartir los gastos de envío. Pero con Amazon Prime, los envíos son gratis, así que no veo ninguna ventaja en ello.

> comprobar primero con otra RAMPS

Por otra parte, no estoy de acuerdo en poner en peligro la integridad de otra impresora. Si le pasara algo a la MEGA de Hija durante las pruebas que propones (imagino que te refieres a probar con otra MEGA) podría conllevar a tener otra impresora fuera de juego.

**Comment by Siotma** [comment]
Además, yo creo que la placa se quemó por culpa de un contacto indirecto de la cadena de anclaje con la electrónica. Tiene pinta de que la parte quemada actuó de fusible evitando daños mayores. De todas formas, cuanto antes pidamos la placa, antes podremos hacer pruebas y volver a tener a Blacky operativa.

> Yo, y podria comprarla sin problemas.

Recuerda solicitar factura acorde con la normativa de subvenciones, disponible [aquí](https://www.uc3m.es/ss/Satellite/Cultura/es/TextoDosColumnas/1371240285442/) (ver artículo 12).

**Comment by Siotma** [comment]
También podemos valorar comprar aquí: https://www.ebay.es/itm/MEGA-2560-R3-USB-CH340-Control-Development-Board-Compatible-Arduino-B0015-/201641182543

Tengo buenas experiencias comprando en esta tienda el año pasado. Dan factura y envían rápido...

**Comment by GioSunrider** [comment]
Si sale mas barato adelante, yo en ebay jamas he comprado nada asi que no tengo opiniones.

**Comment by Siotma** [comment]
Aceptada la compra entonces. Compraré dos unidades para tener una de repuesto y prototipado.

**Comment by Siotma** [comment]
Realicé el pedido y llegó el miércoles. El jueves lo llevé a la nave.

@GioSunrider estuvo realizando el cambio de placa y nos puede contar más detalles...

**Comment by GioSunrider** [comment]
> Edit by Siotma: La placa que se hace referencia en este comentario no es ninguna de las que se compró en esta Issue. Es la que estaba en el robot "Hacha de la muerte", que fue desmantelado y nos dejaron la placa en el armario para ponerla en Blacky.

Hay pocos detalles que añadir, lo primero se subió el Marlin a la placa sin ningún problema y se conecto a la ramps con comprobación de las conexiones. Una vez instalado todo, se procedio a la conexion de la fuente de alimentacion. Se encendio correctamente y al ir a hace Home All, se apago de repente. En ese punto desconecte la fuente de alimentación y efectivamente olia a quemado y el regulador de la nueva placa habia muerto. @Siotma intento sustituirlo por el de la anterior pero no coincidian asi que se queda como tarea pendiente.

**Comment by Siotma** [comment]
En la última reunión, realicé un proceso de diagnóstico de la placa que se quemó:

En la reunión anterior se quemó el regulador de la MEGA, pero comprobé si seguía funcionando por USB: afirmativo, la placa está en buen estado, tan solo le falta el regulador para funcionar alimentada por VIN, por tanto no sirve para las impresoras. El regulador que llevaba es un AMS1117-5.0 formato SOT223. Al desoldar el que tenía, se rompió el pad 2 en la placa, pero está disponible a través del tab, por lo que yo creo que se podría poner uno nuevo. No obstante, no sé si merece la pena ponerle un regulador o dejarla para prototipar por USB. Digo esto, teniendo en cuenta que hay otras dos nuevecitas que compramos (https://github.com/asrob-uc3m/impresoras-asrob/issues/62#issuecomment-386871106).

Actualmente la placa está en el armario, dentro de una bolsa con una nota que explica lo anterior.

Foto: 

![2018_05_17_mega_without_regulator](https://user-images.githubusercontent.com/6171234/40268158-ff006524-5b68-11e8-95a8-9a69fef2e835.jpg)

**Comment by Siotma** [comment]
Aprovechando que tenía una MEGA funcional, pero sin regulador, pensé que era una oportunidad perfecta para diagnosticar el fallo de Blacky que había acabado con el regulador: En una placa sin regulador, no se puede quemar el regulador, y en caso de sobre consumo, al estar conectada por USB, la protección del puerto apagaría todo el sistema. Así lo hice.

Conecté la placa a la RAMPS de Blacky y fui conectando cables poco a poco, comprobando que funcionaba cada uno:
1. Conecté el extrusor y probé a calentar: funcionaba de forma intermitente. Comprobé que la clema de la RAMPS estaba en mal estado y solo hacía contacto si apretabas con el dedo. Sustituí la clema por una nueva y el problema se solucionó. El extrusor calentaba bien.
2. Conecté la cama y probé a calentar. Todo correcto.
3. Cogí un pololu y fui probando todos los zócalos con él, y con el motor del extrusor: los zócalos de X, Y, Z, E0, funcionan correctamente.
4. Cogí todos los pololus y los fui probando en el zócalo del eje X con el motor del extrusor: todos los pololus están en buen estado.
5. Coloqué cada pololu en su posición y fui probando los ejes, finales de carrera incluidos. Todo correcto. Tan solo detecté que un cable del motor del eje Y estaba despeluchado a la altura del conector y corría riesgo de hacer cortocircuito con los pines cercanos. Cambié el crimp y lo dejé saneado.
6. Conecté la pantalla y probé a controlar la impresora desde ella: funcionó correctamente.

A estas alturas la placa tenía todas las conexiones y funcionaba correctamente. El puerto USB no parecía estar sufriendo. Así que me la jugué, flasheé otra MEGA nuevecita y se la puse, conectando todo poco a poco igual que lo he descrito antes.

El resultado fue satisfactorio y di a Blacky por arreglada, coloqué la placa en su sitio y la pusimos a imprimir:

![2018_05_17_blacky_back_live](https://user-images.githubusercontent.com/6171234/40268282-e4c18be6-5b6a-11e8-89e0-d748bc3ecb5f.jpg)
![2018_05_17_blacky_prints_cube](https://user-images.githubusercontent.com/6171234/40268283-e50511e0-5b6a-11e8-81ad-e400bbf93368.jpg)
