### ISSUE TITLE
Cable management en Dédalo

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#63]
Los cables de Dédalo son un peligro para todos y para sí misma.

Ahora que le hemos puesto una placa nuevecita, molaría dejar la impresora en condiciones para que dure funcionando mucho tiempo, para ello propongo, al menos:

- [x] Aumentar la longitud del cable del ventilador de capa, y conducirlo paralelo a los demás cables que van al extrusor.
- [x] Revisar que ningún cable estorba el movimiento de ningún eje.
- [x] Imprimir un soporte donde atornillar la OVM20.
- [x] Imprimir un soporte para la pantalla (por ejemplo [este](https://www.thingiverse.com/thing:848151)).
- [ ] Investigar si se puede modificar el Marlin para poder dar la vuelta el cable del motor Y para que quede orientado igual que los demás.
- [ ] Cambiar el cable de potencia de la cama por otro con mayor sección.

Y como extra:

- [x] EXTRA: quitar todas las bridas y retirar el cableado. 
- [x] EXTRA: Separar todos los cables e identificarlos. 
- [x] EXTRA: Conducirlos con nuevas bridas por las varillas de manera eficiente.

**Comment by JorFru** [comment]
Claramente soy indispensable, me asigno el trabajo de cables.

Percibo que el cable que alimenta la cama caliente puede no ser del grosor suficiente para el amperaje que maneja una cama (entre 10 y 15A) Sugiero cambiarlo, si estáis de acuerdo, ponedlo arriba en el checklist. Recordad que Geonosis calentaba su cable del calentador del extrusor, que son 4 o 5A... hay que tener cuidado con esto por temas de seguridad, por lo tanto más vale prevenir que curar.

**Comment by Siotma** [comment]
En efecto, los cables que manejan mucha corriente sería importante valorar el cambiarlos por los de silicona que tenemos. 

Respecto a los cables de los motores, termistores y finales de carrera, la sensación que me dio ayer es que son suficientemente largos (algunos incluso sobra un buen trozo), pero que llevan tanto tiempo en la misma posicion que están viciados y acartonados. Yo propongo soltarlos completamente y replantear su trazado. Sobre todo hay que evitar que se enreden y que estorben el movimiento de los ejes.

**Comment by David-Estevez** [comment]
Creo que me voy a tener que presentar al título de "Rey de las ñapas"... :see_no_evil: :see_no_evil: :see_no_evil:

**Comment by Siotma** [comment]
He encontrado esta maravilla en un proveedor de confianza de eBay: CADENETAS PORTACABLES!

- [15x20](https://www.ebay.es/itm/Cadena-Portacables-15x20-1m-CNC-Impresora-Carrier-Cable-Drag-Chain-Wire-I0139-/202184716787)
- [10x10](https://www.ebay.es/itm/Cadena-Portacables-10x10-1m-CNC-Impresora-Carrier-Cable-Drag-Chain-Wire-I0138-/202184710341)
- [10x20](https://www.ebay.es/itm/Cadena-Portacables-10x20-1m-CNC-Impresora-Carrier-Cable-Drag-Chain-Wire-I0140-/202184721639)

**Comment by Siotma** [comment]
En la última reunión, @dmarcosm y yo hicimos los siguientes progresos:

- Alargamos el cable del ventilador de capa con los cables existentes en el armario y le pusimos un conector para conectarlo directamente a lo pines de la OVM20Lite.
- Analizamos el cableado de la impresora, y detectamos que había muchos cables con una longitud mayor de la necesaria. Estos cables tenían varias vueltas innecesarias para quedar pegados a las varillas.
- Retiramos la mayor parte de las bridas para liberar los cables y replantear su trazado.
- Recondujimos los cables de:
  - El extrusor, el ventilador de capa y el termistor.
  - El final de carrera del eje Y.
  - El final de carrera del eje Z.

Que @dmarcosm añada si se me ha olvidado algo.

**Comment by Siotma** [comment]
Es urgente disponer de un soporte para dejar la placa instalada. Tal vez nos valga el que tenía la antigua placa, aunque sea de forma temporal. @David-Estevez , podrías traerlo?

**Comment by David-Estevez** [comment]
Sin problema! :+1:

**Comment by David-Estevez** [comment]
Ya los tenéis, están puestos en Dédalo

**Comment by Siotma** [comment]
En la reunión del último jueves continuamos revisando la longitud de los cables y fijamos la placa a la impresora. 

Además, colocamos una cadeneta para conducir los cables de potencia y el termistor de la cama.

Cada vez queda menos para volver a tenerla funcionando.

**Comment by Siotma** [comment]
@dmarcosm tiene nueva información sobre esto :wink:

**Comment by d-marcos-m** [comment]
En la última reunión ya quedaron todos los cables con la longitud deseada y medianamanete colocados (hasta que no tengamos una caja para la placa no terminaría de colocarlos).
Estuvo imprimiendo a la perfección (dentro de lo que cabe) unas piezas para el ventilador de capa de Geonosis (#61) :)

**Comment by CinnabarCinnamon** [comment]
Se ha comenzado el recableado de Dédalo, se ha ajustado (cortar y soldar) las longitudes de los cables de Y y X.

**Comment by CinnabarCinnamon** [comment]
El cableado de Z y Extrusor están a medio camino, Dédalo que inutilizable hasta que se acabe.

**Comment by GioSunrider** [comment]
Se ha colocado ademas el LCD, como se ve en #129

**Comment by CinnabarCinnamon** [comment]
Se da por finalizada la colocación de cables. Cerrando issue.
![dedalo_cableado](https://user-images.githubusercontent.com/44849400/53190017-0c458900-3609-11e9-9a9b-abb929b7b561.jpg)

**Comment by GioSunrider** [comment]
Se ha hecho una prueba de impresion durante la charla de @JorFru para el GUL.

![photo6014942763239452403](https://user-images.githubusercontent.com/10605193/53192629-3ef28000-360f-11e9-98a9-9666730c43bf.jpg)
