### ISSUE TITLE
Comprar regletas para la granja de impresoras

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#64]
Hay que comprar regletas que lleven alimentación hasta la granja de impresoras y sistemas auxiliares.

De momento se ha detectado la necesidad de dos regletas, y se ha medido su longitud:

- [x] Comprar regleta de 5 metros con mínimo 8 tomas de corriente, e interruptor. (Para las impresoras, el router y las raspberrys).
- [x] Comprar regleta de 3 metros con mínimo 5 tomas de corriente e interruptor. (Para poder poner hasta 2 PCs, 2 pantallas y la Arcade).
- [x] Instalar las regletas.

Las compraré esta semana en Bricomart / Leroy Merlin o similar para poder instalarlas en la próxima reuníon.

**Comment by Siotma** [comment]
Hoy he comprado dos regletas:

- 5 metros y 6 tomas con interruptor (dado que el router va a estar conectado permanentemente ya no hacen falta tantas tomas, en un futuro se pueden colgar nuevas regletas de esta.
- 3 metros y 6 tomas con interruptor.

Total 13,98€

**Comment by Siotma** [comment]
En la reunión de ayer, se instalaron las regletas en su lugar:

![2018_05_03_new_grid_extenders_](https://user-images.githubusercontent.com/6171234/39636625-189c1db0-4fc1-11e8-8579-60391b73db53.jpg)

![2018_05_03_new_grid_extenders_connection](https://user-images.githubusercontent.com/6171234/39636628-1a50bd6e-4fc1-11e8-8f1a-9e89a1b02ac3.jpg)

**Comment by David-Estevez** [comment]
Puede que sea conveniente hacerles algún tipo de ASROB-marca para que se sepa que son nuestras (y que, concretamente, son de la granja).
