### ISSUE TITLE
Comprar un MOSFET para Geonosis.

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#67]
@JorFru dijo en #60 que sería buena idea ponerle un MOSFET a Geonosis cuanto antes.

He encontrado [este](https://www.ebay.es/itm/MKS-MOSFET-Extrusor-Cama-Caliente-Impresora-3D-Heating-Control-Bed-Extruder-I093-/202154694034) de un proveedor de confianza de eBay. Sin embargo, los que tenéis una Anet estáis más puestos que yo en el tema...

Tareas:
- [x] Discusión y selección de un MOSFET adecuado.
- [x] Realizar el pedido del MOSFET.
- [x] Recepcionar el MOSFET.
- [x] Instalar el MOSFET en Geonosis.

**Comment by d-marcos-m** [comment]
Ese mismo que propones es el que he comprado yo para mi Anet @Siotma. Diría que es el indicado, aunque creo que @JorFru puede aportar más en este caso.

**Comment by JorFru** [comment]
Todos cumplen con lo que necesitamos

**Comment by GioSunrider** [comment]
En mi caso el que esta es [este](https://www.amazon.es/gp/product/B0714JXQT7/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1). Sin ningun problema en envio y sin ninguna queja de el.

**Comment by Siotma** [comment]
Gracias por vuestro asesoramiento. Damos por bueno entonces el modelo seleccionado.

**Comment by Siotma** [comment]
Realicé el pedido y llegó el miércoles. El jueves lo llevé a la nave y @GioSunrider nos tiene qué contar qué tal se le dio montarlo.

**Comment by GioSunrider** [comment]
Instale el MOSFET sin ningún problema. siguiendo el esquema de conexiones de la siguiente foto.

![3d-piezas-de-la-impresora-controlador-mks-mosfet-para-la-cama-del-calor-extrusora-mos-m jpg_640x640](https://user-images.githubusercontent.com/10605193/40054648-eb1373d8-5845-11e8-8737-996e4d9e3797.jpg)

Para ello tuve que añadir la tercera conexión de la fuente de alimentación, ademas de meter también los cables del ventilador que estaban un poco mal sacados, y fijarlos al marco de Geonosis. Adjunto foto del resultado.

![photo6039848625753926904](https://user-images.githubusercontent.com/10605193/40054726-24f006ac-5846-11e8-8d60-b3a00d5e3974.jpg)

Ademas se probo a ver si calentaba la cama y sin ningun problema. Asi que cierro issue.
