### ISSUE TITLE
Comprar una fuente de alimentación decente para Hija

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#68]
Todos nos acordamos de aquella mala racha de fuentes de alimentación #28 #33 #35 etc..

La fuente de alimentación actual de Hija Resurrection no es de las más prometedoras de las que tenemos. Además, dada su forma, no podemos fijarla a la estructura de la impresora. Según tengo entendido, fuentes de alimentación de este estilo son fiables y además se pueden fijar en impresoras P3steel como Hija:

![imagen](https://user-images.githubusercontent.com/6171234/39409844-32f05a68-4bee-11e8-81c8-990a3675864b.png)

He encontrado varios proveedores:
- eBay [uno](https://www.ebay.es/itm/Fuente-de-alimentacion-12V-30A-360W-Impresora-3D-Switching-Power-Supply-I0015-/201636784333) y [dos](https://www.ebay.es/itm/12V-30A-360W-Impresora-3D-Fuente-conmutada-ALIMENTADOR-LED-TRANSFORMADOR-I0015-/201998587004)
- orballoprinting [uno](https://orballoprinting.com/gl/electronica/77-fuente-de-alimentacion-300w-25a.html)
- hta3d [uno](https://www.hta3d.com/es/fuente-alimentacion-compacta-dc-12v-33a-400w) 

Además, se le podría poner un adaptador:
- [una idea](https://www.ebay.es/itm/Conector-220V-panel-tipo-C14-interruptor-fusible-Arduino-Impresora-3D-K022-/201882461448) con pieza comprada para cables estándar (más esta [carcasa impresa](https://www.thingiverse.com/thing:2158480)).
- [otra idea](https://www.youtube.com/watch?v=eZxkhMWENZU), con pieza impresa.

Tareas:
- [x] Seleccionar el modelo de fuente compatible con el requisito de que debe ser fácil de instalar en la impresora.
- [x] Realizar el pedido.
- [x] Recibir el pedido.
- [x] Imprimir la [pieza adaptadora](https://www.thingiverse.com/thing:2158480).
- [x] Instalar la fuente de alimentación en Hija Resurrection

**Comment by Siotma** [comment]
A mi me mola la de HTA3D.

Edit: por otro lado, la de eBay, parece el mismo modelo y nos ahorraría los gastos de envío.

La de HTA3D solo nos interesaría comprarla junto a los rodamientos igus (#52) y junto al doble extrusor (#53), para compartir gastos.

Edit2: esta [carcasa](https://www.thingiverse.com/thing:2158480) es la caña para combinarla con [esta pieza](https://www.ebay.es/itm/Conector-220V-panel-tipo-C14-interruptor-fusible-Arduino-Impresora-3D-K022-/201882461448).

**Comment by GioSunrider** [comment]
A mi me parece también la mejor opción.

**Comment by Siotma** [comment]
Recibí el paquete el miércoles, y el jueves llevé la fuente a la nave. La fuente y [el conector](https://www.ebay.es/itm/Conector-220V-panel-tipo-C14-interruptor-fusible-Arduino-Impresora-3D-K022-/201882461448) están disponible dentro de una caja en la balda de Printer One.

Si alguien puede imprimir [el adaptador](https://www.thingiverse.com/thing:2158480), se puede instalar en la próxima reunión! :+1:

**Comment by Siotma** [comment]
En la última reunión, Hija imprimió su propia [pieza adaptadora](https://www.thingiverse.com/thing:2158480) para la nueva fuente de alimentación.

En las próximas reuniones se debe instalar la nueva fuente de alimentación y recablear la impresora utilizando para ello las nuevas cadenetas #66 y cables #70 .

Guía de instalación de la fuente: https://www.youtube.com/watch?v=eZxkhMWENZU

Con esto, tambíen se avanzaría en #42 

Foto de la pieza:

![2018_05_17_hija_resurrection_power_supply_adaptor - copia](https://user-images.githubusercontent.com/6171234/40268069-3ed2c1c6-5b67-11e8-846f-7d637086c5cb.jpg)

**Comment by Siotma** [comment]
En la reunión de ayer se comenzó el montaje de la fuente de alimentación de Hija Resurrection.

Fue necesario modificar el cableado que hizo @GioSunrider porque la luz del interruptor se encendía constantemente. Con el nuevo cableado solamente se enciende cuando está en la posoción ON.

También ajustamos la posición de los agujeros para fijar las piezas entre sí con tornillos.

Calibré la tensión de salida a 12,20 V.

Pusimos el cable de alimentación de la RAMPS. Falta otro para la cama caliente y otro para los ventiladores y otros sistemas futuros.

Este es el estado actual:

![2018_05_24_hija_resurrection_new_power_supply_connections](https://user-images.githubusercontent.com/6171234/40560605-c7d0ad4c-605a-11e8-9a9c-68d3cccc7058.jpg)

**Comment by Siotma** [comment]
En la última reunión se finalizó el montaje de la fuente de alimentación de Hija Resurrection.

Se colocaron 3 parejas de cables:
1. AWG16 rojo y negro para la RAMPS (alimentación de la electrónica, potencia del extrusor, motores).
2. AWG16 rojo y negro para la cama caliente (potencia de la cama a través del relé).
3. AWG18 (más finos) para los ventiladores.

La fuente se montó ancló a la impresora con 2 tornillos M4.

![2018_05_31_hija_resurrection_new_power_supply_mounted](https://user-images.githubusercontent.com/6171234/40887351-e5d10ed8-6747-11e8-850b-e97168851dde.jpg)


Los cables que salen de la fuente son demasiado largos, pero esto es adrede, la idea es que tras el cable management de la impresora, veamos cuál es la longitud necesaria y en su caso, los cortemos a medida.

![2018_05_31_hija_resurrection_new_power_supply_mounted_other_side](https://user-images.githubusercontent.com/6171234/40887352-ea2d36a0-6747-11e8-9132-522532df2ad2.jpg)

Los ventiladores se conectorizaron utilizando conectores JST disponibles en el armario, y las bananas que usaban antes, se han devuelto a una de las cajas componentes electrónicos.

![2018_05_31_hija_resurrection_new_power_supply_mounted_wire_details](https://user-images.githubusercontent.com/6171234/40887353-edce8f5c-6747-11e8-8a64-5101b135ccef.jpg)

Se probó el correcto funcionamiento de la fuente de alimentación, probando a calentar la impresora y mover todos los motores.

La fuente que tenía Hija Resurrection ahora está en el armario, y yo propongo que se la pogamos a Blacky...

Issue cerrada.

**Comment by Siotma** [comment]
Piezas actualizadas via 0363e391158485261eb205cfc239e86b738a5702
