### ISSUE TITLE
Mejoras en página de "Gestión de Impresoras" de asrob.uc3m.es

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/impresoras-asrob#7]
Estamos mejorando http://asrob.uc3m.es/index.php/Gestión_Impresoras

- [x] Enlazar con el grupo de Telegram
- [x] Implementando algo como el diagrama de flujo de la figura.
- [x] Implementando scripts que automaticen este proceso ( #8 )

![photo_2016-11-30_21-26-25](https://cloud.githubusercontent.com/assets/4448588/20769804/acf4b5d4-b743-11e6-8dd9-ab0b64f90f85.jpg)

**Comment by andrespy** [comment]
Ya es hora de contribuya un pelin
Aqui esta el diagrama:
![impresorasaldia](https://cloud.githubusercontent.com/assets/17482647/20815625/e826c0c6-b81e-11e6-9786-9d2f666eef28.png)

Si alguien quiere dejarlo más bonito, tengo el archivo del programa dia, que es software gratuito.

@jgvictores @David-Estevez

**Comment by andrespy** [comment]
Ya es hora de que contribuya un pelin
Aqui dejo el diagrama:
![impresorasaldia](https://cloud.githubusercontent.com/assets/17482647/20815778/981e2352-b81f-11e6-8fe1-ab8d7e84aec4.png)

Esta hecho con el programa dia que es software gratuito asi que si alguien quiere mejorar el diagrama cuando sepa donde poner el archivo lo subo para que lo haga.

**Comment by jgvictores** [comment]
Enlazado con grupo de telegram en wiki: http://asrob.uc3m.es/index.php/Gestión_Impresoras

**Comment by Siotma** [comment]
@David-Estevez , @jgvictores . Esta issue es muy antigua y no está en el repo que debe. Sin embargo creo que a día de hoy, ya está más que resuelta puesto que ya no usamos la página de impresoras de la Wiki, y las páginas de [impresoras](http://asrob.uc3m.es/printers/) y [operadores](http://asrob.uc3m.es/printers/operators.html) cumplen la función demandada.

Como mucho, quedaría indicar en la [antigua página de impresoras](http://asrob.uc3m.es/index.php/Gesti%C3%B3n_Impresoras), un enlace a la nueva.

**Comment by David-Estevez** [comment]
Yo movería los "enlaces útiles" al manual de usuario, pondría el cartel enlazando a la nueva página y con eso daría esta issue por cerrada.

**Comment by jgvictores** [comment]
1. Teníamos la idea de sólo poder reservar si está logueado un operario. ¿Esto está hecho? 

2. Nunca hice nada parecido, pero en GitBook puedes acceder con una cuenta de GitHub (aparte de Google, etc). Si lo de (1) no está hecho, sería una opción, no?

**Comment by Siotma** [comment]
> Teníamos la idea de sólo poder reservar si está logueado un operario. ¿Esto está hecho?

Actualmente, está hecho que únicamente personas identificadas con una cuenta de correo UC3M en Google pueden reservar.

> Nunca hice nada parecido, pero en GitBook puedes acceder con una cuenta de GitHub (aparte de Google, etc). Si lo de (1) no está hecho, sería una opción, no?

No entiendo cuál es el objetivo de utilizar cuentas de GitBook. Sin embargo, creo que las propuestas para perfeccionar el sistema de reservas deberían hacerse [aquí](https://github.com/asrob-uc3m/printers-status-webpage/issues/4).

**Comment by jgvictores** [comment]
> No entiendo cuál es el objetivo de utilizar cuentas de GitBook. Sin embargo, creo que las propuestas para perfeccionar el sistema de reservas deberían hacerse [aquí](https://github.com/asrob-uc3m/printers-status-webpage/issues/4).

Sí, me referí a GitBook pero el del Issue mover es igual, como propones [en la issue correspondiente](https://github.com/asrob-uc3m/printers-status-webpage/issues/4#issuecomment-350535856). Totalmente de acuerdo con seguir los desarrollos ahí.

@Siotma Cierra esta issue sin problema, ¡gracias!

**Comment by Siotma** [comment]
Wiki actualizada: http://asrob.uc3m.es/index.php/Gesti%C3%B3n_Impresoras

Manual de usuario actualiado: https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/enlaces_utiles.html
