### ISSUE TITLE
Colocar QR / URL de la web de impresoras cerca de las impresoras

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/impresoras-asrob#71]
Para intentar solucionar casos de amnesia temporal o pereza aguda, ¿qué os parece si imprimimos la url de la web de impresoras (http://asrob.uc3m.es/printers/) en formato QR y/o directamente como URL y pegamos el cartel cerca de las impresoras? 

Un posible sitio sería la estantería de la granja, cuando esté instalada.

**Comment by David-Estevez** [comment]
Dejo por aquí el QR ya creado:

![image](https://user-images.githubusercontent.com/1451819/39479140-9f099a12-4d64-11e8-804c-d6df19b8fe3c.png)

**Comment by d-marcos-m** [comment]
Cuál sería la función? Que la gente reserve las impresoras desde la propia nave, que conozcan la web...?

**Comment by David-Estevez** [comment]
Posibles funciones:

* Acceso directo a estado de las impresoras (operativa/ no operativa).
* Acceso directo a instrucciones sobre cómo ser operador.
* Acceso directo a manuales de uso.
* Acceso directo a hojas de reserva.
* Acceso directo a issues en caso de incidencia.

Todo ello pensando en novatos / personas vagas (me incluyo en lo segundo).

**Comment by d-marcos-m** [comment]
Sugerencia: Y si lo imprimimos en 3D? :smirk: 
Sería imprimir una base cuadrada en filamento blanco, y a mitad de impresión cambiar al filamento negro para la parte del propio QR

**Comment by jgvictores** [comment]
> Sugerencia: Y si lo imprimimos en 3D? :smirk:

[Aquí](https://github.com/asrob-uc3m/robotDevastation-openrave-models/issues/4#issuecomment-373781813) documentamos cómo hicimos uso de https://github.com/welshjf/blender-local-qrcode
