### ISSUE TITLE
Comprar cinta de doble cara para el montaje de la granja

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#72]
Teniendo en cuenta la cantidad de cosas que vamos a montar sobre la granja, me da miedo que el SAV nos lleve a soluciones de dudosa calidad. Teniendo en cuenta que el mobiliario es un bien escaso, y que debe quedar bien instalado, he pensado que:

- Debemos evitar atornillar sobre las mesas o sobre la estantería, para evitar los agujeros.
- Debemos evitar las bridas para sujetar los componentes ya que se pueden mover. Sí que las podríamos usar para sujetar cables.
- Debemos evitar por todos los medios la cinta de embalar, cinta americana o cinta aislante para que no se quede todo pegajoso.

Creo que una cinta de doble cara es una solución ideal, si es de buena calidad y se pone con duidado.

**Comment by d-marcos-m** [comment]
El otro día cuando movimos los armarios salió un rollo muy grande de cinta de doble cara (a menos que no fuese cinta de doble cara)

**Comment by Siotma** [comment]
Hoy he comprado esta cinta en Leroy Merlin: 7,75€.

La idea es que esté disponible en la nave antes de que sea necesaria, de forma de que nadie caiga en la tentación de utilizar ninguna otra cosa. Por las referencias de uso anteriores que tengo, esta cinta pega más que los tornillos, así que hay que usarla con cabeza :sweat_smile: 

Puede que haya algunos retales por el armario, pero así usamos la misma para todo.

Instrucciones:
1. limpiar superficies antes de usar
2. no tocar el adhesivo directamente con los dedos
3. presionar fuerte durante unos segundos tras su instalación.

![cinta ceys](https://user-images.githubusercontent.com/6171234/39543593-f9b3106e-4e4b-11e8-80e0-2ce6f4a4bb95.jpg)

**Comment by Siotma** [comment]
> El otro día cuando movimos los armarios salió un rollo muy grande de cinta de doble cara (a menos que no fuese cinta de doble cara)

Recuerdas dónde estaba? Mañana lo podemos mirar.

**Comment by d-marcos-m** [comment]
> Recuerdas dónde estaba? Mañana lo podemos mirar.

Armario de la derecha

**Comment by David-Estevez** [comment]
> Puede que haya algunos retales por el armario, pero así usamos la misma para todo.

No, no, no son retales, es un señor rollo.

**Comment by Siotma** [comment]
En la última reunión, dejé la cinta de doble cara en el armario.

Es cierto que tenemos otra, pero es distinta:
- La que tenemos es gruesa y acolchada, y fácil de romper con los dedos. La verdad es que pega bastante, pero no es resistente a esfuerzos. Es buena candidata para sujetar cosas con poco peso, o para instalaciones temporales.
- La nueva es más fina y va reforzada con una malla, como la cinta americana. Pega una barbaridad, así que esta debe usarse solo para instalaciones permanentes.
