### ISSUE TITLE
Una torre no funciona

### ISSUE THREAD

**Issue by DiegoGarciaX2** [asrob-uc3m/impresoras-asrob#75]
Emite un pitido

**Comment by David-Estevez** [comment]
Algún dato más sería de ayuda:

* ¿Qué torre es la que falla (de las tres o cuatro que tenemos)?
* ¿Cómo es el pitido (los ordenadores suelen pitar de forma distinta según el error)?

**Comment by GioSunrider** [comment]
Encargo a @DiegoGarciaX2 que traslade la issue a actas.
