### ISSUE TITLE
Renovacion de las fotos de la impresoras

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#76]
Hoy se va a proceder a la renovacion de las fotos de las impresoras 3D. Para ello me llevare la Camara Reflex con un flash externo y con ayuda de los circuitos impresos haremos una especie de "estudio" improvisado. Posteriormente procesare y editare las imagenes con ayuda de Photoshop y colgaremos los resultados. Tanto las fotos originales como las procesadas se almacenaran en esta issue y en cada una de las carpetas de las impresoras.

**Comment by GioSunrider** [comment]
Utilizando a @Siotma como soporte de sujeccion del circuito impreso usado y se han tomado las siguientes fotos.

![impresoras_0001](https://user-images.githubusercontent.com/10605193/40067202-ff939f7a-5865-11e8-82e9-6b8178279122.JPG)

![impresoras_0002](https://user-images.githubusercontent.com/10605193/40067204-ffb68062-5865-11e8-9e81-72a77b2be85b.JPG)

![impresoras_0003](https://user-images.githubusercontent.com/10605193/40067205-ffe8d800-5865-11e8-9e06-2337e6fd45f1.JPG)

![impresoras_0004](https://user-images.githubusercontent.com/10605193/40067206-001684bc-5866-11e8-9c1a-559a99dbe1f6.JPG)

**Comment by JorFru** [comment]
Qué pulcritud por favor! <3

**Comment by David-Estevez** [comment]
Me ha costado entender lo que era el "Circuito impreso" (estaba pensando en PCBs) :joy:

**Comment by GioSunrider** [comment]
El resultado merece la pena :P

**Comment by GioSunrider** [comment]
Se han subido las fotos al Drive tanto RAW como PNG y se ha actualizado la pagina web con dichas fotos.
