### ISSUE TITLE
Comprar un cable para la tarjeta microsd de Geonosis

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#77]
La posición del MOSFET (#67) dificulta un poco la colocación de la tarjeta SD en Geonosis...

Podría ser buena idea comprar un cable como este para tener el puerto de la SD más a mano. Desde un punto de vista de un uso intensivo, también de esta manera evitamos que de tanto meter y sacar la tarjeta en la placa, esta pueda acabar deteriorándose.

![71 a 5rfijl _sx355_](https://user-images.githubusercontent.com/6171234/40268366-5707b710-5b6c-11e8-9905-135e383e07b6.jpg)

**Comment by GioSunrider** [comment]
Dado a que se va a realizar la conexión por octoprint no seria necesario la compra de este cable.
