### ISSUE TITLE
Configurar y documentar el PC de ASROB

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#78]
Slic3r ha sacado por fin la versión 1.3.0 stable.

Esta versión permite hacer virguerías con los perfiles, recomiendo echar un vistazo las notas: https://github.com/slic3r/Slic3r/releases/tag/1.3.0

Principalmente creo que nos interesa por:
- Las pruebas que he hecho con versiones beta han dado como resultado calidades de impresión mucho más altas que con cualquier otra versión que he probado. Los resultados del slicing son mucho más inteligentes.
- Puedes elegir cualquier parámetro como "acceso directo" y estará disponible para cambiarlo desde la ventana principal.
- Slicing adaptativo: utiliza altura de capa variable para adaptarse fielmente a la forma de las piezas.
- Con este Slic3r se puede prescindir de Repetier, lo que facilitaría la vida a la hora de mantener los perfiles actualizados.
- Es compatible con Octoprint (aunque no sé cómo exactamente).
- Ahora que tenemos por delante una importante tarea de puesta a punto de los perfiles, sería bueno partir de la última versión para obtener los mejores resultados.
- Tengo un perfil bastante bueno del que podemos partir.

Pido ayuda a @David-Estevez y a @jgvictores para ayudarnos a la hora de instalarlo, para que aparezca en el menú inicio y sea ejecutable desde la sesión de invitado. De hecho, creo que tanto vosotros como nosotros agradeceríamos que se documentara el proceso necesario para conseguir esto.

Tareas:
- [ ] Decidir si se instalará Slic3r 1.3.0 en los equipos.
- [ ] Instalar Slic3r 1.3.0 y hacerlo accesible desde el menú inicio, y ejecutable desde la sesión de invitado.
- [ ] Desarrollar los perfiles de impresión.
- [ ] Documentar el uso de este nuevo software a nivel usuario.
- [ ] Accesos directos de cada una de las instancias de Octoprint.
- [ ] Configuración de la sesión de invitado (actualmente está un poco muerta)

BONUS:
Si se decide instalar Slic3r 1.3.0 propongo instalar primero una nueva distribución de [Lubuntu](https://help.ubuntu.com/community/Lubuntu/GetLubuntu) por aquello de tenerlo todo actualizado, que sea estable y que nos dure mucho tiempo.
- [x] Decidir si se instalará una nueva versión de Lubuntu.
- [x] Buscar una versión con fama de ser estable.
- [x] Instalar Lubuntu.
- [x] Documentar los resultados.

**Comment by Siotma** [comment]
Esto principalmente estaría relacionado con los problemas de estabilidad que nos ha dado la versión 14.04 actualmente instalada.

Además, la instalación de Slic3r actualmente está dando problemas porque los nuevos perfiles a veces no se guardan y al reiniciar el ordenador se pierden los cambios.

Por último, viendo que tenemos una torre en mal estado (#75 ) puede ser un buen conejillo de indias sobre el que probar todo esto que propongo.

**Comment by jgvictores** [comment]
He estado jugando con `Slic3r 1.3.1-dev` ([`master`](https://github.com/slic3r/Slic3r) de [hace 6 días](https://github.com/slic3r/Slic3r/tree/ae7fdfe227ef65cf565db87c1d92a40978013bea)) sobre Ubuntu 16.04 y todo bien. Usé el comando `apt` de  https://github.com/slic3r/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux#ubuntu-1604 para instalar las dependencias, y las tres líneas de https://github.com/slic3r/Slic3r/wiki/Running-Slic3r-from-git-on-GNU-Linux#build-slic3r para compilar.

Buenas impresiones con todos los parámetros por defecto; simplemente ajustar las temperaturas y el diámetro del filamento. Nada más en particular que comentar. Antiguamente todo estaba en un `.ini`, y ahora está troceado en 3 ficheros `.ini` (print/filament/printer) pero los parámetros son los mismos.

Yendo a la propuesta específica:
- `slic3r-1.3.0-linux-x64.tar.bz2` parece bastante autocontenido, y `Slic3r-1.3.0-x86_64.AppImage` lo debería ser (creo que es tipo `snap`, que hacen portables). Y de fuente si no. :+1: 
- Pese a esto, pensando en cualquier otro software que se quiera meter a los PCs, me inclino un poco más por 16.04 que 18.04. A favor de 16.04 es la comodidad de la mayor parte de la documentación actual de cualquier cosa incluye los nombres de los paquetes de 16.04. A favor de 18.04 es que cada día todo tenderá más hacia 18.04. :smile: 

PD: Detalles de instalación de Lubuntu en los anexos de https://github.com/asrob-uc3m/impresoras-maintenance-manual-i3

**Comment by Siotma** [comment]
La idea es que el proceso sea fácil, fiable, fácil de documentar y que dure. Pero lo que funcione hoy también funcionará dentro de un año si es estable. La idea no es volvernos locos y actualizar todos los días. Una vez el sistema esté levantado y funcione bien, se puede quedar así largo tiempo hasta que haya motivos suficientes para actualizar (copia de seguridad mediante). 

Si ahora está más documentada la 16.04, tal vez sea mejor idea usar esa.

**Comment by d-marcos-m** [comment]
Ayer quedó el ordenador actualizado a Lubuntu 16.04, sin problemas :+1:

**Comment by d-marcos-m** [comment]
Seguimos en esta issue para configurar y documentar el PC de las impresoras. Podemos hacer uso de anteriores issues como #2 y #3 para sacar información de tareas que se han completado anteriormente.

**Comment by GioSunrider** [comment]
En la reunion de ayer se habilito una mesa fija para poder volver a darle uso al ordenador.

**Comment by MrTommyGuns** [comment]
En la ultima reunión estuve jugando un poco con el PC y añadí a Cura (tiene una versión un poco vieja pero aparentemente tira guay) una impresora y además se añadió el perfil de la misma (Spicy, que siendo del rollo de Hija, Blacky y Dedalo se podrian usar igualmente) y de paso uno que me descargué para testear a Geonosis.
Queda pendiente probar que funciona todo correctamente, pero tiene buena pinta y está preparado para poder slicear alguna pieza sin necesidad de que todos los miembros lleven su ordenador para poder imprimir.

**Comment by MrTommyGuns** [comment]
Se ha estado usando el ordenador en la reunión de hoy para slicear unas cuantas piezas y se ha hecho sin mayor problema del que supone manejar un ordenador antiguo, así que por mi parte cerraba esta issue que me da que está caducada y el PC ya es funcional
