### ISSUE TITLE
Cable management en Hija Resurrection

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#79]
Ahora que Hija Resurrection ya tiene nueva fuente de alimentación (#68) ha llegado el momento de asear el cableado, con ayuda de las últimas adquisiciones de cables (#70) y cadenetas portacables (#66).

Tareas:

- [ ] Identificar el mejor camino de deberían seguir los cables (recomiendo planificar cadenetas en los tres ejes).
- [ ] Imprimir las piezas necesarias para sujetar las cadenetas a la impresora.
- [ ] Modificar la longitud de los cables para que puedan seguir el camino desde su origen hasta su destino.
- [ ] Colocar las cadenetas.
- [ ] Comprobar que la impresora puede alcanzar cualquier posición y que ningún cable estorba ni limita su movimiento.
- [ ] Comprobar que ningún cable cuelga de la impresora.

Finalizando esto, se avanzaría en #42

**Comment by jorgercobo** [comment]
En la reunión del 31 de octubre se avanzó con los cables de la parte posterior:

![image](https://user-images.githubusercontent.com/9537923/48623861-3bfe4880-e9ab-11e8-93f7-aab1154bbb54.png)
![image](https://user-images.githubusercontent.com/9537923/48623866-44568380-e9ab-11e8-8c75-cf84f5e443ff.png)

**Comment by CinnabarCinnamon** [comment]
La pieza que iba a adaptar la sujeción de la cadena a la estructura de Hija se ha partido. Hay que reimprimirla.

**Comment by CinnabarCinnamon** [comment]
@Siotma ¿Tienes algún modelo de enganche entre el extrusor de Hija/Blacky y la cadena?

**Comment by CinnabarCinnamon** [comment]
Hemos encontrado estas dos piezas.



[E3DV6_Chain_Stepper_Mount_V4.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842117/E3DV6_Chain_Stepper_Mount_V4.zip)
[E3DV6_Open_Chain_Long_Solo_V4.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842118/E3DV6_Open_Chain_Long_Solo_V4.zip)

**Comment by GioSunrider** [comment]
cuando comencemos el cable managment de hija, podemos aprovechar para colocarle los rodamientos nuevos de #52

**Comment by MrTommyGuns** [comment]
Dejo constancia por aquí de que se intentó realizar y dejar de la mejor manera posible este asunto, pero debido a falta de material (aka bridas) hay que darle un repaso.

Por otro lado sería interesante imprimir una caja para la electrónica que facilite este punto, ya que la que había esta destrozada.

**Comment by GioSunrider** [comment]
sugiero ahora que los cables tienen la medida correcta, colocar las cadenas y que queden mas ocultos, tal y como refleja el primer comentario de la issue.
