### ISSUE TITLE
Calidad de las impresiones de Dedalo

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#81]
Ultimamente Dedalo, cada vez que imprime tiene perdida de pasos del motor y su calidad no es la de esperar. Pongo foto del ultimo resultado. Hay que investigar mas este problema.

![photo5895414819824184717](https://user-images.githubusercontent.com/10605193/42160590-15116ba4-7df8-11e8-844a-1b00b9817d21.jpg)

**Comment by d-marcos-m** [comment]
Al cambiar la placa de Dédalo a la OVM20 Lite, hemos ganado el soporte para ajustar los drivers de los motores con los potenciómetros que esta tiene. Sería un buen primer paso ajustarlos para ver si se corrigen esas pérdidas de pasos :+1:

**Comment by JorFru** [comment]
Hemos subido un poquito la corriente de los drivers. 
Hemos seguido esta guía. http://www.dima3d.com/motores-paso-a-paso-en-impresion-3d-iii-calibracion-de-corriente/
La OVM en teoría es: I = V x 2
Antes de tocar hemos medido 0.250V en cada driver. Eso son 0.5A

Lo hemos dejado en 0.350V en cada driver (excepto en Z que lo hemos dejado a 0.250V). Lo cual son 0.700A de corriente.


Los drivers dan ás corriente girando en sentido antihorario. Y menos corriente en sentido horario.
Hemos notado que los drivers se calentaban un poco más, pero no más de 60ºC
Con ventilación de electrónica no se nota ninguna temperatura anómala.

**Comment by d-marcos-m** [comment]
Al subirlos ha mejorado la impresión?

**Comment by GioSunrider** [comment]
El próximo día hay que realizar pruebas de impresión, si salen bien podremos dar vida de nuevo a Dédalo.

**Comment by GioSunrider** [comment]
Dédalo en principio está operativa. Procedo a cerrar la issue.
