### ISSUE TITLE
Spicy caldito from la abuela

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#82]
Préstamo de una máquina Anet A8, propiedad de @jorfru , a favor de Printer One.
La máquina se entregó el lunes, 17 de septiembre  del 2018, después de muchos meses de promesas que parecían que nunca se iban a cumplir.
La máquina se entrega precintada. Se precisa de montaje.

Condiciones del préstamo:
La máquina se debe montar.
La máquina se debe cuidar.
La máquina se puede mejorar y cambiar piezas, pero no se pueden cambiar más del 50% de las piezas, ya que perdería la potestad sobre la máquina. 
El préstamo se puede terminar en el momento que cualquiera de las dos partes lo desee.

Disfrutad de la bicha y, por favor, no montéis la H al revés!

Este es el sitio mágico que alberga todos los trucos y prácticas recomendables para la A8. Tratadlo como oro en paño. https://trello.com/b/X1HL9kIf/03anet-a8

Mejoras que consederamos necesarias de implementar

- [x]  Soldar cables de la cama
- [x] Colocar MOSFET en la cama
- [ ] Mejorar rigidez de la estructura
- [x] Mejorar refrigeración de capa
- [ ] Implementar autolevel
- [x] Cable management
- [x] Actualizar el firmware a la última versión

**Comment by JorFru** [comment]
A new hope
![](https://www.larioja.com/noticias/201701/14/media/cortadas/aneto-k30G-U2113362395337nH-575x445@La%20Rioja.jpg)

**Comment by JorFru** [comment]
![photo_2018-09-17_13-38-12](https://user-images.githubusercontent.com/11017088/45621015-2342e680-ba7f-11e8-860d-8568a2b6528b.jpg)
Spicy caldito from la abuela

**Comment by JorFru** [comment]
La ANET llegó justo en el momento oportuno. En La Nave de ASROB se congregaron nueve nuevas personas en la primera reunión de PrinterOne del curso
![photo_2018-09-18_00-25-24](https://user-images.githubusercontent.com/11017088/45653775-72b60080-bad9-11e8-85ea-4d29ddde44d7.jpg)
![photo_2018-09-17_13-38-14](https://user-images.githubusercontent.com/11017088/45653779-75185a80-bad9-11e8-8d54-4f844c66c1b2.jpg)
Vídeos del montaje:
https://www.youtube.com/watch?v=dK14sc66EE8
https://www.youtube.com/watch?v=Sgs6Ly7aKj8

Después del montaje, se imprimió una pieza de prueba. Un calicat llavero, por fin un cubo de calibración con verdadera utilidad!
![photo_2018-09-18_00-43-22](https://user-images.githubusercontent.com/11017088/45654449-f8d34680-badb-11e8-8697-402a13520026.jpg)

**Comment by d-marcos-m** [comment]
Añadida carpeta de la Anet al repositorio de impresoras! https://github.com/asrob-uc3m/impresoras-asrob/tree/master/Anet(Provisional)

**Comment by David-Estevez** [comment]
Hay que darla de alta en la web/bot?

**Comment by d-marcos-m** [comment]
> Hay que darla de alta en la web/bot?

Yo no lo haría hasta que tengamos nombre definitivo. Así evitamos luego tener que entrar a cambiarlo otra vez :D

**Comment by GioSunrider** [comment]
Foto de la Anet acabada.

![photo5884398181465304651](https://user-images.githubusercontent.com/10605193/46417213-6f518480-c729-11e8-9dc5-4008a1f82032.jpg)

**Comment by d-marcos-m** [comment]
> Hay que darla de alta en la web/bot?

Ahora sí hay que darle de alta! Spicyyy!!

**Comment by JorFru** [comment]
Hoy se ha hecho el cable management.
Asigno a la gente que me acuerdo que ha participado. Quien falte, que se apunte.

Foto del logro desbloqueado:
![photo_2018-10-16_21-56-07](https://user-images.githubusercontent.com/11017088/47043759-bfe7c980-d18e-11e8-9f9b-e7f6715dbdaa.jpg)

**Comment by GioSunrider** [comment]
> > Hay que darla de alta en la web/bot?
> 
> Ahora sí hay que darle de alta! Spicyyy!!

Ya esta la issue puesta, keep calm, hoy le hemos hecho las fotos. Mañana las subire y se le podra dar de alta.

**Comment by David-Estevez** [comment]
Ya está dada de alta en la web

**Comment by GioSunrider** [comment]
Dado que las mejoras no están previstas y se pueden realizar en issues separadas, cierto la issue  del montaje. Gran trabajo Chichos!
