### ISSUE TITLE
Cambio Extrusor Blacky

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#83]
Al igual que en hija se propone un cambio completo del extrusor. @Siotma tiene un modelo que iria perfecto para blacky, por lo que le invoco para que como en hija nos diga las piezas y el modelo.

**Comment by Siotma** [comment]
En su día yo me compré este extrusor y va de maravilla, sobre todo porque está pensado para usarse tanto para extrusión directa como para bowden:

https://es.aliexpress.com/item/Best-price-J-head-Hotend-with-cooling-Fan-for-1-75-3-0mm-12v-V6-bowden/32810935651.html?spm=a2g0s.9042311.0.0.XbTp01

**Comment by Siotma** [comment]
La idea de este extrusor es que lleva el filamento a través de un mismo tubo de teflón desde la zona de empuje directamente hasta la zona caliente, por lo que no hay interfaces donde pueda quedar atascado. Desatascar este extrusor es tan fácil como cortar el trozo de tubo donde esté el atasco, en el peor de los casos.
En mi experiencia esto no es necesario ya que el plástico desliza por el interior del tubo sin problema aunque esté frío: he llegado a quitarle el filamento a mi impresora sin calentar y solamente hay que hacer una pequeña tracción para conseguirlo.

El concepto es el siguiente:

![imagen](https://user-images.githubusercontent.com/6171234/45563062-7aad4080-b84c-11e8-91e3-5604b826be8e.png)

**Comment by d-marcos-m** [comment]
Las piezas a imprimir serían las mismas que en el caso de Hija @Siotma ?

**Comment by Siotma** [comment]
Sí, mi intención es que ambas impresoras utilicen el mismo sistema. 
**Pero**, una vez instaladas las piezas de #84 en Hija, se debería revisar qué modificaciones o mejoras se quieren añadir antes de imprimir un nuevo kit para Blacky.

**Comment by GioSunrider** [comment]
Propongo que para la próxima reunión Hija empiece a imprimir las piezas del extrusor para blacky.

**Comment by Siotma** [comment]
Correcto :+1: 

Hay que tener en cuenta que algunas piezas ya están impresas con su actual extrusor, por lo que no hace falta imprimirlas todas.

Esto es lo que hay que imprimir:

- 2 piezas Remix del [L3K](https://www.thingiverse.com/thing:512338), pero diseñado para poder meter el tubo de teflón hasta el Barrel:
  - [x] [1x Wade_L3K_custom_flange_1.75_v2_mirrored.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2394024/Wade_L3K_custom_flange_1.75_v2_mirrored.stl.zip)
  - [x] [1x Wade_L3K_custom_body_1.75_centered.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2384181/Wade_L3K_custom_body_1.75_centered.stl.zip)

- Creación propia:
  - [x] [1x Body_E3dv6_Washer.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393912/Body_E3dv6_Washer.zip)
  - [x] Extra ventilador de capa: [1x Blower_duct.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2394029/Blower_duct.zip)

**Comment by Siotma** [comment]
Lo pongo para considerarlo: Blacky es del departamento y ponerle un nuevo extrusor puede ser un cambio bastante significativo... Tal vez habría que consultarlo y/o solicitar la financiación del extrusor por parte del Departamento para que no corran el riesgo de ir perdiendo porcentaje de posesión sobre la impresora :laughing:

**Comment by GioSunrider** [comment]
Me parece perfecto, @David-Estevez, ¿podrias ponerte tu en contacto par ver la solucion del tema?

**Comment by David-Estevez** [comment]
:+1:

**Comment by David-Estevez** [comment]
Lo he consultado con el jefe de departamento y me ha dado el ok tanto al cambio como a la financiación por parte del departamento. 

Pasadme los enlaces de lo que queréis comprar y hacemos el pedido.

**Comment by Siotma** [comment]
La modalidad que yo propongo sería la de trueque: el extrusor ya lo hemos comprado con la subvención, pero nos hacen falta otras piezas para otras impresoras. En breve postearé una lista con enlaces.

**Comment by Siotma** [comment]
El extrusor costó 9.24€ (ver [aquí](https://github.com/asrob-uc3m/impresoras-asrob/issues/85#issuecomment-425716268)). Sin embargo, un extrusor equivalente vale más de 20€ en España (ver [aquí](https://fervi3d.com/extrusion/116-extrusor-e3dv6-completo-clon.html)).

Propongo como trueque la compra de 7 unidades de rodamiento **Igus RJ4JP 01-08 - Equivalente a Lm8uu** por un valor de 1,30€/unidad, total 9,10€ más envío.

Enlace al artículo: https://fervi3d.com/mecanica/380-igus-rj4jp-01-08-equivalente-a-lm8uu.html

El proveedor propuesto es solamente orientativo. Si se encuentra el mismo producto en otro proveedor más conveniente no habría problema.

**Comment by Siotma** [comment]
He encontrado un enlace de Amazon, donde se pueden comprar 8 rodamientos por 9,83€: https://www.amazon.es/Igus%C2%AE-Rodamiento-deslizamiento-drylin%C2%AE-rj4jp/dp/B01M4JZ81S/ref=sr_1_1?m=A39KIAQT9XODN8&s=merchant-items&ie=UTF8&qid=1542565300&sr=1-1&th=1

**Comment by GioSunrider** [comment]
Sigue en #119

**Comment by GioSunrider** [comment]
Reabrir para que cuando pueda @David-Estevez nos confirme la decisión del departamento.

**Comment by GioSunrider** [comment]
Bloquea a #52 cuando @David-Estevez nos confirme dicha decision.

**Comment by David-Estevez** [comment]
Los rodamientos han sido pedidos. Os aviso cuando lleguen.

**Comment by David-Estevez** [comment]
Seguimos en #52
