### ISSUE TITLE
Nuevo extrusor para Hija

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-asrob#84]
En la próxima reunión llevaré un Hotend para montar en Hija.

Sería ideal que además se llevaran impresas las siguientes piezas:

- [x] [1x Carro del eje X y 1x prensa de la correa](https://www.thingiverse.com/thing:701087)

- 3 piezas del [L3Kv2](https://www.thingiverse.com/thing:1855673):
  - [x] [1x Wade_L3K_v2_Idler.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393904/Idler.zip)
  - [x] [1x Wade_L3K_v2_Idler_hodler.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393905/Idler_hodler.zip)
  - [x] [1x Bearing_Washer.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393911/Bearing_Washer.zip)

- 2 piezas Remix del [L3K](https://www.thingiverse.com/thing:512338), pero diseñado para poder meter el tubo de teflón hasta el Barrel:
  - [x] [1x Wade_L3K_custom_flange_1.75_v2_mirrored.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2394024/Wade_L3K_custom_flange_1.75_v2_mirrored.stl.zip)
  - [x] [1x Wade_L3K_custom_body_1.75_centered.stl.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2384181/Wade_L3K_custom_body_1.75_centered.stl.zip)

- Creación propia:
  - [x] [1x Body_E3dv6_Washer.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2393912/Body_E3dv6_Washer.zip)
  - [x] Extra ventilador de capa: [1x Blower_duct.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2394029/Blower_duct.zip)

Que empiece el reto!

**Comment by Siotma** [comment]
La idea es que los que estén interesados en imprimir cualquiera de las piezas, se apunten con un comentario para evitar duplicaciones...

**Comment by d-marcos-m** [comment]
Este carriage es al que hay que meterle una tuerca a mitad de impresión? Si es así, que tipo de tuerca exactamente? 
Yo puedo imprimir un set entero, pero aviso de que será morado/rosa de BQ.

**Comment by d-marcos-m** [comment]
Antes de imprimir creo que mejor estar seguros. Hemos estado mirando los STLs y no nos cuadra que sea para un Bowden, básicamente porque la pieza que sujeta el motor y la que sujeta el hotend es la misma, o sea que sería directo.
Entonces, nos planteamos que vamos a seguir con un extrusor directo en vez de un bowden o qué hacemos @Siotma  
Por otra parte, faltan piezas como los engranajes y la pieza que sujeta el rodamiento, o reutilizamos las que ya tiene la impresora?

**Comment by Siotma** [comment]
La tuerca es una M4, pensaba que lo ponía en la página de la pieza. Cuando lo imprimí yo, no me cabía M4 y tuve que poner M3, que también va bien pero baila un poco.

Los STLs tienen la ventaja de servir **tanto para extrusión directa como para bowden**. En un primer momento lo pondríamos como directo y una vez la impresora esté funcional se puede imprimir un par de piezas para convertirlo en bowden.

Los engranajes yo diría que se pueden reutilizar los del mismo extrusor, porque ya lo hicimos con Blacky.

Lo que sí se me olvidó fueron las piezas del idler.

Voy a actualizar el primer post con nuevas piezas.

**Comment by Siotma** [comment]
Tal y como se puede ver en [esta issue](https://github.com/asrob-uc3m/impresoras-asrob/issues/45#issuecomment-368879177), no hace falta cambiar los engranajes.

**Comment by Siotma** [comment]
Actualizado primer post con más información.

**Comment by Siotma** [comment]
Aún más piezas disponibles ! 

Recomiendo no hacer más de un kit hasta que lo hayamos probado y visto los problemas...

**Comment by d-marcos-m** [comment]
He añadido los botoncitos de checklist para ir marcando las que hayamos impreso para este set. Para evitar esto basicamente: 

> La idea es que los que estén interesados en imprimir cualquiera de las piezas, se apunten con un comentario para evitar duplicaciones...

**Comment by d-marcos-m** [comment]
Like por los soportes ya incluídos en el STL de la pieza más grande. Acabo de descubrir que no eran parte de la pieza :D

**Comment by d-marcos-m** [comment]
![image](https://user-images.githubusercontent.com/14359236/45814555-3a2f4600-bcd6-11e8-8b02-5551f7498d1b.png)

**Comment by Siotma** [comment]
Las piezas se montaron en la reunión del pasado lunes, junto con un extrusor que aporté yo mientras se gestiona la compra de los nuevos en #85 

El montaje mecánico quedó resuelto, tan solo falta:

- [x] Apretar bien el hoten en caliente para que no se desenrosque, y 

- [ ] hacer el cableado. 

Este es el estado actual:
![1](https://user-images.githubusercontent.com/6171234/46222936-3349a880-c352-11e8-9471-43c34de0f96e.jpg)

Entre las ventajas que presenta este extrusor está el hecho de que no hay que andar enroscando y desenroscando tornillos para meter y sacar el filamento, sino que basta con retirar la lengüeta con los dedos para liberarlo:

![2](https://user-images.githubusercontent.com/6171234/46222997-58d6b200-c352-11e8-9a6c-e1a9da902c29.jpg)
![3](https://user-images.githubusercontent.com/6171234/46223002-5b390c00-c352-11e8-8365-d693416fff51.jpg)

El tubo de teflón va desde el hobbed bolt hasta el heatblock por lo que el filamento nunca cambia de interfaz mientras está frío, lo que previene los atascos:

![4](https://user-images.githubusercontent.com/6171234/46223069-8ae81400-c352-11e8-9e3b-588dffbb06b7.jpg)

**Comment by Siotma** [comment]
Cosas interesantes de este extrusor:

- No es necesario retirar la lengüeta para insertar un nuevo filamento. Se puede introducir por la parte de arriba y una vez llegue al hobbed bolt, dar la orden al extrusor de que extruya para que lo termine de llevar hasta el nozzle.
- No es necesario retirar la lengüeta para extraer el filamento. Se puede dar la orden al extrusor de que retraiga para que lo saque.

De hecho, a partir de Marlin 1.1.6 se pueden configurar hasta 5 comandos personalizados que desde la pantalla LCD permiten hacer lo anterior (Midna es el nombre de mi impresora):

```
/**
 * User-defined menu items that execute custom GCode
 */
#define CUSTOM_USER_MENUS //MIDNA
#if ENABLED(CUSTOM_USER_MENUS)
  #define USER_SCRIPT_DONE "M117 User Script Done"
  #define USER_SCRIPT_AUDIBLE_FEEDBACK
  #define USER_SCRIPT_RETURN  // Return to status screen after a script

  #define USER_DESC_1 "Preheat for PLA" //MIDNA
  #define USER_GCODE_1 "M140 S" STRINGIFY(PREHEAT_1_TEMP_BED) "\nM104 S" STRINGIFY(PREHEAT_1_TEMP_HOTEND) //MIDNA

  #define USER_DESC_2 "Preheat for FFx" //MIDNA
  #define USER_GCODE_2 "M140 S" STRINGIFY(PREHEAT_2_TEMP_BED) "\nM104 S" STRINGIFY(PREHEAT_2_TEMP_HOTEND) //MIDNA

  #define USER_DESC_3 "Filament in" //MIDNA
  #define USER_GCODE_3 "G92 E0\nG1 E80 F600\nG1 E90 F120\nM400\nM300 P100\nM18" //MIDNA

  #define USER_DESC_4 "Cooldown" //MIDNA
  #define USER_GCODE_4 "M140 S0\nM104 S0" //MIDNA

  #define USER_DESC_5 "Filament out" //MIDNA
  #define USER_GCODE_5 "G92 E0\nG1 E-90 F600\nM400\nM300 P100\nM18" //MIDNA
#endif
```

- Habría que comprobarlo para estar seguros, pero con este extrusor es posible extraer el filamento incluso con el hotend frío, moviendo con cuidado la rueda del extrusor en sentido de retracción hasta escuchar un "clac".

**Comment by Siotma** [comment]
En lo que respecta a esta issue, @dmarcosm debería tener el honor de cerrarla :tada:

**Comment by d-marcos-m** [comment]
> En lo que respecta a esta issue, @dmarcosm debería tener el honor de cerrarla

No! Falta la tobera del ventilador!!

**Comment by JorFru** [comment]
En la última reunión medio-completamos estas dos tareas:

```
Apretar bien el hotend en caliente para que no se desenrosque, y

hacer el cableado.
```
Queda terminar los dos puntos anteriores y montar el ventilador de capa para completar esta issue

**Comment by MrTommyGuns** [comment]
En la reunión no llegamos a apretar el hotend (no sé se si hizo fuera de ella) y los cables falta ponerlos bien con bridas (no dio tiempo)

**Comment by JorFru** [comment]
Gracias Tommy, queda pendiente entonces, editado.
Cuando termiéis esta issue, acuérdate de marcar los checkboxes de arriba y cuando esté todo completo (ventilador de capa instalado) se podrá cerrar la issue.

**Comment by Siotma** [comment]
En la última reunión (8 de octubre), continué los trabajos en Hija:
- Deshice el apaño del cableado, ya que podía quedar pellizcado entre la estructura. Se acordó que el cableado del extrusor se debe guiar con una cadeneta: #66 #99 
- Soldé el ventilador blower de 40x40x20 para el ventilador de capa.
- Añadí una vuelta de cinta aislante en la zona donde se ancla el hotend para evitar que se mueva, ahora queda bien fijo.
- Apreté a conciencia el hotend, en frío y luego en caliente.
- Realicé una prueba de cubo de impresión, satisfactoria:

![cubo 8_oct](https://user-images.githubusercontent.com/6171234/46904736-51361200-cee9-11e8-95ae-0e3f59b3a02d.jpg)

- También comprobé que el nuevo extrusor admite retracciones grandes sin problema de atascos: llegué a probar más de 20mm de retracción.
- Probé con éxito a insertar el filamente utilizando el motor del extrusor.
- Probé con éxito a extraer el filamento utilizando el motor del extrusor.
- Probé con éxito a extraer el filamento en frío utilizando el motor del extrusor.

**Comment by Siotma** [comment]
Tras ello, puse a Hija a imprimir su propio ventilador de capa, que quedó estupendamente:

![vent capa 8_oct](https://user-images.githubusercontent.com/6171234/46904772-c73a7900-cee9-11e8-9501-e051dea4b46a.jpg)

**Comment by Siotma** [comment]
Me consta que el día 10 @GioSunrider lo instaló en Hija, pero aún quedan cosas por hacer:
- Poner mirando para el otro lado el ventilador del hotend, para que el cable no quede estorbando.
- Apretar los tornillos que sujetan el ventilador a la pieza azul.
- Añadir un segundo tornillo para sujetar la pieza azul a la rosa y que no baile.
- Regular bien la altura de la pieza azul.
- Apretar los dos tornillos de sujección para fijar la altura.
![vent capa montado 10_oct](https://user-images.githubusercontent.com/6171234/46904798-31ebb480-ceea-11e8-84db-1f9a049cc548.jpg)

**Comment by Siotma** [comment]
Piezas actualizadas via 0363e391158485261eb205cfc239e86b738a5702

**Comment by Siotma** [comment]
Hoy se ha completado el montaje del ventilador de capa. Se han realizado [dos pruebas de impresión](https://www.thingiverse.com/thing:922740) con Hija Resurrection que han dado como resultado una nueva caja para RaspberryPi:

![16_oct_raspi_box](https://user-images.githubusercontent.com/6171234/47047000-bf533100-d196-11e8-9ba6-eecb4386ea5f.jpg)

La renovación del extrusor de Hija ha sido todo un éxito y se puede dar la issue por cerrada. @dmarcosm procede.
