### ISSUE TITLE
Cristal para Geonosis

### ISSUE THREAD

**Issue by GioSunrider** [asrob-uc3m/impresoras-asrob#86]
Dado que Geonosis se encuentra actualmente sin cristal, me propongo a gestionar su colocación. Para ello dispongo de un cristal (de nevera) de grandes dimensiones que actualmente se encuentra en mi pueblo. El próximo día que vaya para allá lo traeré y solo haría falta con un cortavidrios, del que también dispongo hacerlo a medida.

**Comment by IviPartida** [comment]
Perfecto, el dia que lo hagas si necesitas ayuda cuenta conmigo🤙🏾

**Comment by GioSunrider** [comment]
Ayer lleve (Por fin) el cristl para Geonosis, con la ayuda de @MrTommyGuns y @L4g0 cortamos el cristal y se instalo en geonosis.

![photo5924675439874387224](https://user-images.githubusercontent.com/10605193/47070050-bdb65700-d1f0-11e8-957c-9f9bec7eb445.jpg)
