### ISSUE TITLE
Propuestas y votación nombre nueva impresora - Anet A8

### ISSUE THREAD

**Issue by d-marcos-m** [asrob-uc3m/impresoras-asrob#88]
Esta issue es para proponer nombres para la nueva impresora (https://github.com/asrob-uc3m/impresoras-asrob/issues/82) y su posterior votación. Dejad los nombres propuestos en un comentario y antes de la próxima reunión votaremos las propuestas que haya para dejar el firmware cambiado de forma definitiva.

Las propuestas hasta el momento son las siguientes: 
- Spicy Caldito
- Easy Fire
- Charmander
- Mustafar 
- Arden Lyn 
- Darth Fire
- Red Hot Chili Printer

**Comment by MrTommyGuns** [comment]
Spicy!

**Comment by JorFru** [comment]
Yo le daría un nombre que recuerde la habilidad innata que tiene esta máquina por arder espontáneamente.

**Comment by IviPartida** [comment]
Easy Fire

**Comment by d-marcos-m** [comment]
Charmander

**Comment by David-Estevez** [comment]
Mustafar

**Comment by GioSunrider** [comment]
Siguiendo la temática del resto de impresoras propongo Arden Lyn.
1. Porque arde fácilmente
2. Para el que no la conozca dejo el link: http://es.starwars.wikia.com/wiki/Arden_Lyn

**Comment by JorFru** [comment]
A mí me mola el rollo SW
Como es negra, podría llamarse Darth Fire

**Comment by David-Estevez** [comment]
Red Hot Chili Printer

**Comment by GioSunrider** [comment]
Kaiburr, son los cristales que dan poder a los sables de luz.

**Comment by L4g0** [comment]
Spicy 💯

**Comment by d-marcos-m** [comment]
Voten! Abierto hasta el domingo!
(INVALID)

**Comment by GioSunrider** [comment]
Nuevo formulario, debido a los errores del anterior. Queda abieto hasta el domingo.
https://goo.gl/forms/gM2HX9JpW5oOw5Cd2

**Comment by GioSunrider** [comment]
El resultado de la votación ha sido el siguiente:

![votacion2](https://user-images.githubusercontent.com/10605193/46263659-39868300-c512-11e8-95d0-69f0c12bd2c5.png)

Luego el nuevo nombre de la impresora es Spicy. Se ha añadido la etiqueta correspondiente y asigno a @dmarcosm para que realice el cambio de carpeta correspondiente.

**Comment by David-Estevez** [comment]
Maldita sea! por 1!!

Tooooooongo! Toooongo!

**Comment by d-marcos-m** [comment]
> asigno a @dmarcosm para que realice el cambio de carpeta correspondiente.

Hecho
