### ISSUE TITLE
Actualización firmware de Spicy Caldito

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#89]
@GioSunrider cambió el firmware de Spicy Caldito, del firm original de la ANET a un Marlin modificado por él, que no es la última versión.

Los resultados antes y después del cambio de firmware:
![photo_2018-09-19_16-46-54 2](https://user-images.githubusercontent.com/11017088/45762372-832bbf80-bc2e-11e8-868e-3270fa6f6e8a.jpg)
El calicat de la izquierda es con el firm original, el de la derecha es con el Marlin de Gio.
Ambos el mismo GCODE

Presiento que hay que ajustar aceleraciones.

**Comment by d-marcos-m** [comment]
Creo que esto deberíamos ponerlo en la issue de puesta a punto, para evitar tener 8 issues solo de la Anet :(

**Comment by JorFru** [comment]
Organízalo tú entonces
Mi idea era abrir una issue para cada parte de la máquina.

- Firmware/placa
- Extrusor
- mecánica

por ejemplo, como hay con las otras máquinas.

**Comment by Siotma** [comment]
Un gran número de issues no son un problema si solamente se requiere una o dos acciones máximo para resolverlas. Las issues estilo "puesta a punto de X" no han demostrado funcionar porque se pierden los avances en las diferentes tareas y los nuevos las ven con miedo de todo el trabajo que hay que hacer. Pienso que el sistema de issues está concebido para un enfoque como el que propongo.

Los veteranos deberíamos intentar abrir issues lo más "atómicas" posibles, aunque sean muchas. De esta manera cada una no duraría abierta más de una o dos semanas desde que se empieza a trabajar hasta que se termina, mientras que ahora tenemos issues a medias, que llevan abiertas meses y nadie se acuerda de por dónde se iba.

**Comment by d-marcos-m** [comment]
> Organízalo tú entonces
> Mi idea era abrir una issue para cada parte de la máquina.
> 
> * Firmware/placa
> * Extrusor
> * mecánica
> 
> por ejemplo, como hay con las otras máquinas.

No lo decía con ánimo de ofender a nadie. 



> ... Las issues estilo "puesta a punto de X" no han demostrado funcionar ...

Quizá entonces deberíamos replantear los "puesta a punto de X" como proyectos y no como issues, ya que se quedan ahí eternamente sin ser cerrados nunca.

**Comment by d-marcos-m** [comment]
En la próxima actualización hay que aprovechar a cambiar el nombre por Spicy, tal y como ha salido elegido en #88

**Comment by JorFru** [comment]
Actualmente está flasheada con el nombre "Spicy", creo recordar.

En esta issue voy a documentar el tema de ajuste de aceleraciones en Spicy. Ya que desde que se cambió el firmware original, no imprime igual de bien, y posiblemente sea esta razón. Buscaré los ajustes que traía por defecto y los pondré en el Marlin que tiene actualmente. Creo que se puede hacer desde la pantalla, o hace falta flashear.

**Comment by d-marcos-m** [comment]
Aunque se pueda hacer desde la pantalla, diría que mejor dejarlo cambiado en el firmware (por lo que pueda pasar). Así mismo, aprovecharía para actualizar a Marlin 1.1.9 :D

**Comment by GioSunrider** [comment]
Cómo dice @dmarcosm es la oportunidad para cambiar al nuevo marlin, y de paso hacerlo en todas las impresoras. Así los nuevos también aprenden esa parte.

**Comment by GioSunrider** [comment]
En la última reunión actualice el firmware de Spicy por Marlin 1.1.9., el mismo que tengo yo en casa, añadidos los custom comanda y habilitado el cambio de filamento. Mañana subiré los archivos de configuración al repo.

**Comment by GioSunrider** [comment]
Subidos archivos en 21e93f3 
Tienen el añadido de lenguaje ya que esta pensado para PLA y PETG, en vez de ABS y PLA.
