### ISSUE TITLE
Problemas pendientes en la reparación de HIJA

### ISSUE THREAD

**Issue by jorgercobo** [asrob-uc3m/impresoras-asrob#9]
Solucionado el problema del atasco en el extrusor, queda pendiente comprobar si funciona correctamente, reordenar el cableado que ha habido que desensamblar y de algún modo enganchar la tapa del ventilador del extrusor que está suelta en la parte superior.

**Comment by jorgercobo** [comment]
PD: Problema anterior: #5

**Comment by Siotma** [comment]
Hay una lista más detallada de problemas en #11 cierro para evitar duplicidades
