### ISSUE TITLE
Piezas para Geonosis! 

### ISSUE THREAD

**Issue by d-marcos-m** [asrob-uc3m/impresoras-asrob#90]
Geonosis necesita piezas nuevas para mejorar su estructura! 

De momento solo son 2 piezas para los motores de X e Y, y ya veremos si necesitamos algo más adelante :) 
- [x] Sujecciones motores X e Y: https://www.thingiverse.com/thing:2613150/files

**Comment by GioSunrider** [comment]
Rehacer el ventilador de capa lo necesita, pero no me acuerdo que piezas eran.

**Comment by d-marcos-m** [comment]
No es este, es parecido. Pero me gusta más, porque no queda el ventilador tan vertical y no tiene tantas posibilidades de morir de un golpe: https://www.thingiverse.com/thing:2659499/files

**Comment by GioSunrider** [comment]
Pero no es el mismo ventilador, esa pieza no valdría, nuestro ventilador el aire sale por un lateral no por toda la superficie

**Comment by d-marcos-m** [comment]
Quizá este: https://www.thingiverse.com/thing:2828421/files
(aunque lo de que el nuestro sea vertical no sería un problema porque hay una pieza-adaptador imprimible)

**Comment by JorFru** [comment]
Opinión personal justificable:
Ese ventilador radial enano que trae la Tronxy y que estáis obcecados en
usar es una absoluta basura.
Merece la pena gastarse 4 pavos en un ventilador nuevo. Un 40mm axial, o
uno radial más grande, como el de la A8.

Saludos xD

**Comment by d-marcos-m** [comment]
Me suena que en la última compra vino un ventilador centrífugo, más grande que el que tiene ya geonosis, pero que me confirme @Siotma

**Comment by Siotma** [comment]
Efectivamente, compramos dos: #53

**Comment by GioSunrider** [comment]
Compraria otro compatible con el nuevo extrusor que se instale en Blacky y pondría uno en Geonosis, como lo veis?

**Comment by d-marcos-m** [comment]
No entiendo tu pregunta @GioSunrider. Si ya tenemos 2 comprados, y uno va para blacky, ya nos sobra uno para geonosis, no?

**Comment by GioSunrider** [comment]
No, se compraron 2, uno para Hija y otro para Blacky. No nos sobran.

**Comment by d-marcos-m** [comment]
Ah, vale. No lo había pensado :+1:

**Comment by Siotma** [comment]
Con uno de los ventiladores que tenemos, se podría plantear algo como esto: https://www.thingiverse.com/thing:2819859 Yo propongo ponerlo primero solamente en un lado (el que no tenga endstop para no liarla), porque ahora solo tenemos uno. Si para cuando llegue el envío de AliExpress vemos que hace falta uno en cada lado, se puede poner otro.

**Comment by Siotma** [comment]
Alguien se ha puesto ya con este reto?

**Comment by Siotma** [comment]
En la última reunión, Hija imprimió las dos sujecciones de motores:

![24_oct_geonosis_corners](https://user-images.githubusercontent.com/6171234/47604695-72c0ee80-d9fd-11e8-9a41-8f6a5627edc0.jpg)

Respecto a los ventiladores de capa, @jorgercobo y yo estuvimos dándole vueltas. Hemos pensado en volver a colocar las piezas originales y poner una tobera por dentro para dirigir mejor el aire al disipador y que no pegue en el hotend. Cuando tengamos claro cómo debe hacerse, abriremos otro reto de impresión.
