### ISSUE TITLE
Tampones para sello Feria de Asociaciones

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#91]
Necesitamos tener impreso, para disponer de ello el miércoles, el siguiente item que consiste en un tampón para sello con el logo de ASROB. Se usará para validar a la gente que pase por el stand de ASROB en la gymkhana.
La pieza no tiene el tamaño correcto todavía, hay que escalarlo.
2-3cm de ancho, con 3cm de altura para que se pueda coger con la mano sin mancharse de tinta, a ser posible.
[ASROBstamp.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2410172/ASROBstamp.zip)

También he preparado otro sello, de regalo, para obtener más puntos en el reto de impresión. Está dentro del zip.

Hoy a mediodía voy a llevar filamento flexible de FFF color "azul topacio" para que se imprima.

**Comment by GioSunrider** [comment]
Lo imprimo a la hora de comer en casa en PLA, a la hora de comer, y lo llevo esta tarde.

**Comment by GioSunrider** [comment]
El sello quedo en el armario listo para su uso, se colgara posteriormente foto de él.

**Comment by JorFru** [comment]
Yo tengo uno en filaflex, pero no quedó nada bien la primera capa.
Lo probaremos.

**Comment by Siotma** [comment]
Cómo fue este reto?

**Comment by GioSunrider** [comment]
Falta la foto que no lo hicimos pero bueno, el plan chupa poca tinta pero sirvió para su cometido.

**Comment by JorFru** [comment]
![photo_2018-10-01_03-06-43](https://user-images.githubusercontent.com/11017088/46265485-3053e100-c527-11e8-9812-7a39d40143f7.jpg)
Imprimí esto, descuidando la máquina y la primera capa (la importante para el resultado final del sello) no quedó del todo bien.
Al volver a intentar imprimirlo tuve un atasco interesante.

El día D por problemas organizativos no pude llevar la pieza impresa a la feria.

L

**Comment by JorFru** [comment]
@GioSunrider te mereces cerrar la Issue
