### ISSUE TITLE
Mejoras extrusor Spicy Caldito

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#92]
He impreso esta pieza con Spicy y la he colocado
![photo_2018-09-24_19-03-59](https://user-images.githubusercontent.com/11017088/45966938-b904e580-c02c-11e8-800d-ca87491fd7cc.jpg)
El archivo: https://www.thingiverse.com/thing:2133328

**Comment by Siotma** [comment]
Gracias, Jorfru! Por su aspecto, creo que es posible que esta pieza sea compatible con uno de los ventiladores que compramos hace algún tiempo, así que no conviene perderla de vista :wink:

**Comment by d-marcos-m** [comment]
> así que no conviene perderla de vista

@JorFru si es posible, súbela a a carpeta de la Anet!
