### ISSUE TITLE
Formación como Operador

### ISSUE THREAD

**Issue by MrTommyGuns** [asrob-uc3m/impresoras-asrob#93]
Hola wenas,

Me gustaría formarme como operador, así que lo pongo por aquí de forma oficial, por si algún voluntario que tenga algún espacio libre que nos vaya bien a los 2 me quiere formar.

O vamos, decidme la mejor opción que creáis vosotros si es así.

Thaanks!

**Comment by GioSunrider** [comment]
Mira bien donde poner la issue. 
https://github.com/asrob-uc3m/operadores/issues
