### ISSUE TITLE
OVM20 ANET edition para Geonosis

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#95]
Staticboards nos ha regalado su última creación para que la probemos como betatesters. Conviene instalarla lo antes posible para ir reportando a Javier Loureiro (Staticboards) las sugerencias y bugs de la nueva placa.

La placa original de la Tronxy irá al armario. El MOSFET que actualmente lleva Geonosis se moverá a Spicy #96

**Comment by d-marcos-m** [comment]
Observaciones de otros betatesters:

- Los conectores de alimentación de la cama y el extrusor tienen los nombres en la placa intercambiados. Hay que conectar los cables del extrusor a donde pone hotbed y los de la cama donde ponga hotend.
- tiene dos entradas de alimentación, una de 5A y otra de 11A. Ya lo comenté hace poco pero bueno, es como la ramps, hay que conectar solo el de 5A si no usamos cama caliente y en nuestro caso, que si, hay que alimentar ambos.
- en el github de staticboards hay un firmware subido ya preparado para la anet. Tiene configuración para ahorrar memoria en menús y tal, porque podía dar problemas de falta de memoria al poner autolevel. Habrá que editar cosas porque la nuestra es corexy. Ejes x e y llevan tmc2208, y es la versión 1.1.9 de Marlin

**Comment by JorFru** [comment]
Tenemos un problema, se nos ha quemado un componente de la placa, parece que se trata de un regulador. Posiblemente sea el que da los 5V, pero no estoy seguro. [Tenemos esta documentación](https://www.staticboards.es/wp-content/uploads/2018/09/anet8.pdf), hay que pedirle el layout de componentes a Javier para averiguar de qué componente se trata.

Yo creo que esto se ha quemado porque los conectores de final de carrera no coinciden cable a cable. Por lo tanto se han conectado mal y han cortocircuitado los 5V. O bien han sido los sensores de temperatura mal conectados, aunque me parece muy raro.
![imagen](https://user-images.githubusercontent.com/11017088/46572769-b2129700-c98b-11e8-9b85-35b4b243d3bd.png)

En todo caso hay que pasar reporte a Javier y enterarnos de qué ese ese componente y con qué reemplazarlo. (lo haremos nosotros mismos).

**Comment by d-marcos-m** [comment]
Sigo sin entender por qué están conectados así. No habría sido mejor ponerle conectores?

**Comment by JorFru** [comment]
> Sigo sin entender por qué están conectados así. No habría sido mejor ponerle conectores?

Los conectores que venían eran de dos pines y no vi ninguno de tres en el armario.
Consulté el esquemático y ponerlo así me pareció la mejor manera. Parece que el pin de en medio no está conectado a nada, y el conector de dos sólo vale para pines correlativos.
![imagen](https://user-images.githubusercontent.com/11017088/46572851-0a966400-c98d-11e8-96ab-6264259fbef0.png)

**Comment by d-marcos-m** [comment]
Pues no sé. Ahora después digo a Javier que os meta a uno de los dos en el grupo de betatesters, que yo estoy hasta arriba ahora.

**Comment by JorFru** [comment]
De cabeza entro en ese grupo.
No tengo tiempo
pero para hablar de electrónica estoy siempre disponible.

**Comment by Siotma** [comment]
Puntualizar que no ha sido un regalo: https://github.com/asrob-uc3m/impresoras-asrob/issues/87

**Comment by JorFru** [comment]
Componentes pedidos. Estarán aquí a partir del 28 de octubre, creo.
Los pago de mi bolsillo, cuesta 0.12€.

**Comment by Siotma** [comment]
@JorFru , algún dato interesante del último día para que conste?

**Comment by JorFru** [comment]
El proveedor se equivocó y me mandó AMS1117-3.3 en vez de AMS1117-5.0
Conseguiré los reguladores correctos para instalarlos el lunes o martes después de la OSHWDem

**Comment by Siotma** [comment]
Parece que la placa quedó reparada en la última sesión. @JorFru trató de flashear Marlin 1.1.9 sin éxito.

Hoy he estado investigando. He conseguido instalar la placa de la Anet en Arduino IDE siguiendo el tutorial: https://trello.com/c/QRIYELJA/311-configurar-arduino-ide-para-actualizar-el-firmware-a-partir-de-c%C3%B3digo-fuente

También he editado los archivos de configuración (adjuntos). Más info en la página oficial: https://www.staticboards.es/productos/ovm20anet/  y en github: https://gist.github.com/staticboards/441ee5d194fd3f69d54b6cffbad19161

Sin embargo, no he sido capaz de subir ningún firmware a la placa porque parece que no tiene bootloader. @dmarcosm dice que puede ocurrir que al programarla se borre, así que igual eso fue lo que le ocurrió a @JorFru . Habrá que usar un ISP, en ASROB tenemos este el USBTinyISP. En el siguiente enlace aparecen los esquemáticos de los conectores: https://cdn-learn.adafruit.com/downloads/pdf/usbtinyisp.pdf

Según @dmarcosm hay que conectarlo así.
![ovm_isp](https://user-images.githubusercontent.com/6171234/48800050-fcb45c80-ed08-11e8-87a7-48eb7250108f.jpg)


[Configuration_Geonosis.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2601415/Configuration_Geonosis.zip)

**Comment by GioSunrider** [comment]
Me gustaría que actualizados el estado de la placa, si esta es funcional ya mismo, podéis proceder a cerrar la issue

**Comment by GioSunrider** [comment]
Siguiendo el tutorial de staticsboards, que @Siotma proporciono, logre subir con exito el marlin 1.1.9, aunque los fichero que ha y en el repo de @dmarcosm estan mal configurados, ya que la pantalla ni la placa eran las correctas. 
Cuando se fue a comprobar la placa ocurrio lo siguiente....

![photo5825823451842195177](https://user-images.githubusercontent.com/10605193/50282959-b4e23b80-0454-11e9-969b-581c6be31f9f.jpg)

Se rompio el conector usb, por lo uqe planteo dos soluciones al problema.
1. Si @JorFru puede repararlo, tiene via libre para hacerlo ya que la placa podemos actualizarla via programador, pero, no podemos conectarla a octoprint.
2. Retornar a la paca original de TronXY

**Comment by JorFru** [comment]
Creo que puedo hacerlo.
Me propongo como plazo las dos primeras semanas de Enero.

Si necesitáis la máquina con el USB en funcionamiento antes de este periodo, podéis hacer lo que queráis, pero no me puedo comprometer a hacerlo en una fecha concreta.

**Comment by GioSunrider** [comment]
No, no ha prisa, es más SAV, ya que todavía no hemos visto a geonosis quemando plástico. Pero no hay problema en tenerla parada, hay otras 4 Impresoras. Así que por mi parte tienes vía libre para ponerte con ella cuando puedas, te dejo encargado de esta issue para que hagas lo que creas mejor.

**Comment by Siotma** [comment]
> 
> 
> Siguiendo el tutorial de staticsboards, que @Siotma proporciono, logre subir con exito el marlin 1.1.9, aunque los fichero que ha y en el repo de @dmarcosm estan mal configurados, ya que la pantalla ni la placa eran las correctas.

Según dices, utilizaste las fuentes de @dmarcosm , sin embargo, yo te había dejado un zip con la configuración en [mi post](https://github.com/asrob-uc3m/impresoras-asrob/issues/95#issuecomment-440414586). Supongo que no lo viste. Estuve configurándolo un buen rato y busccando información para asegurarme de lo que hacía... debería funcionar bien.

**Comment by GioSunrider** [comment]
Pues la verdad que no lo vi, seria subir ese a ver si funciona, pero antes hay que arreglar la placa.

**Comment by JorFru** [comment]
Jorfru ejecutó y @GioSunrider miró.
Siento no dejarte el placer de soldarla tron. La siguiente te la haces tú.
Lo blanco es cianocrilato+bicarbonato.
Estará disponible para montarse en la siguiente reunión.


![photo_2019-01-26_04-03-28](https://user-images.githubusercontent.com/11017088/51781869-655ff100-211f-11e9-8353-c25a6f50d35d.jpg)
![photo_2019-01-26_04-03-30](https://user-images.githubusercontent.com/11017088/51781870-655ff100-211f-11e9-984a-a58cfd252831.jpg)

**Comment by GioSunrider** [comment]
Yo seria incapaz de haber hecho esa ñapa, n ote preocupes, el credito es todo tuyo! El proximo dia hay que ponerse con geonosis a muerte!

**Comment by GioSunrider** [comment]
Se ha intalado y subido el marlin que @Siotma configuro, funciona perfectamente menos por el LCD que ha y que configurarlo.

**Comment by GioSunrider** [comment]
Sigo sin poder arreglarlo, para poder subir el marlin hay poner la placa tipo Anet V1.0 (Optiboot) para que se suba correctamente.

![527a364e-a765-49be-95fc-1884067beb91](https://user-images.githubusercontent.com/10605193/51986425-810d2380-24a0-11e9-9648-0f4d045e6a6d.jpg)

**Comment by JorFru** [comment]
Yo en su día también hice muchos intentos para poner a funcionar esa pantalla LCD y no lo conseguí.

**Comment by Siotma** [comment]
> 
> 
> Se ha intalado y subido el marlin que @Siotma configuro, funciona perfectamente menos por el LCD que ha y que configurarlo.

Mentira! Hoy @GioSunrider y yo hemos intentado hacer pruebas de movimiento con Geonosis y al hacer homing, el regulador de 5V HA VUELTO A ARDER! :tired_face: 

Necesitamos volver a colocar la placa antigua y poner la impresora a funcionar. Lleva casi un año en la asociación y ahora que tiene un V6 no puede estar parada...

**Comment by JorFru** [comment]
Cuál es el estado actual?
La OVM se ha vuelto a freír? La reparo si hace falta.

Me da mucha pena ver esta máquina parada, sobre todo por el extrusor grueso que tiene y no le estamos dando uso.

**Comment by MrTommyGuns** [comment]
Yep, sigue frita...
Yo le volvería a poner la placa anterior y pa lante a funcionar...
Si no me equivoco también tenemos placas donadas del hackatón. Podemos ver cuales rentan para cada impresora
Para nuestra impresora casta necesitariamos una plaquita de estas open supongo

**Comment by GioSunrider** [comment]
Mi idea es poner la ovm 20 lite para la nueva a democratizar, una buena mecánica con una buena placa. La ovm anet sigue frita, quedamos en que habria que reparar y probarla una a una, y a geonosis ponerle su placa original.

**Comment by GioSunrider** [comment]
@JorFru cambio de nuevo el regulador. Esta vez ardio nada mas encender. Hemos decidido quitar la placa y volver a la orginal. Ahora vuelve a funcionar y se estan haciendo n uevas pruebas de impresion.

**Comment by GioSunrider** [comment]
Doy esta issue por cerrada dado que no se va a utilizar esa placa.

**Comment by JorFru** [comment]
Pruebas de impresión satisfactorias. La placa antigua funciona correctamente, su firmware (Marlin 1.1.6) parece funcionar correctamente.
