### ISSUE TITLE
MOSFET de la cama para Spicy

### ISSUE THREAD

**Issue by JorFru** [asrob-uc3m/impresoras-asrob#96]
Geonosis, después de recibir la OVM20 ANET edition #95 , donará su MOSFET a Spicy. Hay que instalarlo.

**Comment by d-marcos-m** [comment]
También hay un mosfet que doné yo hace 2 semanas en el armario. Quizá interesaría ponerselo al extrusor de Spicy, queda a vuestra decisión.

**Comment by JorFru** [comment]
Un poco overengineered pero me mola la idea.

**Comment by JorFru** [comment]
En la reunión del 3 de octubre se empezó con el montaje de este nuevo componente, pero no se terminó. Se puede imprimir actualment pero sólo con cama fría.
Urgente terminar esta issue.

**Comment by DiegoGarciaX2** [comment]
El soporte del Mosfet se ha impreso he instalado en Spicy

**Comment by Siotma** [comment]
Funciona correctamente?

**Comment by GioSunrider** [comment]
Afirmativo, siguieron el esquema de conexiones que realizamos en su dia en la issue de #67
