### ISSUE TITLE
Ideas Proyectos - Subvenciones curso 2018-2019

### ISSUE THREAD

**Issue by d-marcos-m** [asrob-uc3m/impresoras-asrob#97]
Vayamos dejando aquí las ideas de proyectos que se nos vayan ocurriendo, ya que no tardando mucho tendremos que pedir las subvenciones de este curso (sabemos fechas @GioSunrider?)

**Propuestas:**

- Subvención "Mantenimiento y mejora de la granja de impresoras"
    - Enclosure con candado para filamentos
    - Cerrar la granja (molaría que se abriese sola al logearse en el PC :D) 
- Prusa blackbelt
    - Cinta (??) 
    - Motor tocho en Y? 
- Mejoras y materiales para nuestras impresoras:
    - Filamentos
    - Perfilería (AM8)
    - Doble extrusor Blacky (?)
    - Mejoras "simples" (aka autolevel, bases, etc...)

**Comment by GioSunrider** [comment]
Todavía no tengo ni idea, pero si, de momento una de mantenimiento de la granja de impresoras hay que pedir.

**Comment by d-marcos-m** [comment]
Como idea loca propongo montarnos una Prusa Blackbelt, es decir, añadirle una cinta motorizada a una de las impresoras tipo prusa que tenemos. El proyecto en sí no sería demasiado complicado, ya que sería, a grandes rasgos, usar el motor del eje Y para hacer girar una cinta de un material X alrededor de la cama caliente. Habría que ver si habría que aumentar el tamaño de la impresora por debajo para que cupiese el mecanismo, pero no lo veo muy complicado :)

**Comment by JorFru** [comment]
Yo quiero empezar a manejar perfilería y montar una AM8 o una Hypercube o güadever

**Comment by GioSunrider** [comment]
Yo pediría dos subvenciones entonces, una de mantenimiento del parque de impresoras y otra de proyecto de mejora. En la de mejora podemos incluir perfilería y demás, así también tenemos dinero y margen de maniobra.

**Comment by d-marcos-m** [comment]
Lo de la AM8 lo veo muy factible, además no nos costaría demasiado. Quizás haría en general una subvención de "Creación y mejora de impresoras", y detallar dentro todo lo que queremos hacer

**Comment by GioSunrider** [comment]
Yo lo decía por la compra de filamento! Qué cogería solo una subvención para la compra de varios tipos de filamento e investigar.

**Comment by d-marcos-m** [comment]
> Yo lo decía por la compra de filamento! Qué cogería solo una subvención para la compra de varios tipos de filamento e investigar.

Subvención para material? Tipo perfilería, filamento, mejoras de impresoras (aka autolevel, bases, etc..)

**Comment by d-marcos-m** [comment]
> Todavía no tengo ni idea, pero si, de momento una de mantenimiento de la granja de impresoras hay que pedir.

Realmente, qué hay que mejorar exactamente en la granja de impresoras? O sea, tenemos algo pensado?

**Comment by GioSunrider** [comment]
Perfilería, y bueno la tronxy necesita una buena mano de muchas cosas, igual sería la que se llevaría todo el presupuesto.

**Comment by d-marcos-m** [comment]
Pero eso no es mejora de la granja de impresoras, si no mejora de las impresoras.

**Comment by GioSunrider** [comment]
Y justo, una subvención de materiales, pero solo de impresión, para dejarles bien colocados, para que nadie se los pueda llevar. Tipo enclosure pero además que sean de distintos tipos, PLA, Nylon, Petg, ABS,...

**Comment by d-marcos-m** [comment]
> Y justo, una subvención de materiales, pero solo de impresión, para dejarles bien colocados, para que nadie se los pueda llevar. Tipo enclosure pero además que sean de distintos tipos, PLA, Nylon, Petg, ABS,...

Acabo de actualizar la lista. Yo creo que algo así iría bien, y luego ya veremos qué más podemos hacer en la granja. Quizá cerrarla o algo así.

**Comment by GioSunrider** [comment]
Exacto, esa es otra que se me olvidaba, el cerrar la granja

**Comment by d-marcos-m** [comment]
Propongo también transformar una de las impresoras que tenemos con RAMPS a multicolor, con doble extrusor, lo cual sería muy interesante para los soportes solubles :)

**Comment by d-marcos-m** [comment]
- Cambio de extrusor de Dedalo, a 1.75mm
- Añadir laser engraver/cutter a una impresora (anet, por ejemplo)

**Comment by GioSunrider** [comment]
Propongo aglutinar, una unica subvencion de "mejora y mantenimiento de la granja de impresoras." De esta manera tenemos margen para aplazar ideas y asi tambien dejamos subvenciones para el resto de la asociacion.

**Comment by d-marcos-m** [comment]
Yo pienso que deberíamos pedir al menos 2 subvenciones separadas. Por no generalizarla tanto y que luego quizá algo no podamos pasarlo por esa, pero el experto en subvenciones es @Siotma.

**Comment by GioSunrider** [comment]
Hay que ver cuantas subvenciones se piden en general de asociacion, porque si pedimos todos, dos igual son muchas.

**Comment by d-marcos-m** [comment]
Si es una asociación con mucha actividad no creo que eso suponga un problema. De todas maneras, hay... 3 grupos? Malo será que todos pidamos 2. Y aún así 6 tampoco son tantas.

**Comment by MrTommyGuns** [comment]
En la reunión de Asociaciones que hicimos con África el año pasado nos dijo que cada vez había más Asociaciones y se pedían más subvenciones y que la uni podía regular un poco ese tema... Aún así yo diría de pedir lo que nos haga falta y que nos aprueben lo que se pueda y listo

**Comment by David-Estevez** [comment]
Uno de los años (no recuerdo si el pasado o antes de eso) sí que estaba regulado el número máximo por asociación. Una posible "trampa" es pedirla a título individual como alumno, que también se puede.

**Comment by d-marcos-m** [comment]
> Uno de los años (no recuerdo si el pasado o antes de eso) sí que estaba regulado el número máximo por asociación. Una posible "trampa" es pedirla a título individual como alumno, que también se puede.

En vez de a título personal, se podrían pedir en nombre del grupo? O tiene que ser asociación per se? De todas formas yo creo que no saldrán tantas peticiones para todo asrob, así que no me preocuparía.

**Comment by David-Estevez** [comment]
O a título personal, o bajo una asociación.

**Comment by GioSunrider** [comment]
Vale chicos, hay que saber que queremos pedir exactamente. @dmarcosm no te vengas arriba que hay que aglutinar todo lo que podamos, dado a que tiene pinta que vamos a estar limitados, también hay que pensar que nos dará tiempo a hacer menos de un año.

**Comment by David-Estevez** [comment]
Como he sugerido por el grupo de RoboFactory, primero apuntad qué es lo que queréis pedir (si hubiese dinero/subvenciones ilimitadas) y a partir de eso trabajamos.

También estaría guay que hicieséis un desglose de las cosas que harían falta en cada proyecto y cuánto estimáis que costarían.

A partir de eso haremos nuestra magia de siempre.

**Comment by GioSunrider** [comment]
Cierro issue dado que ya se ha solictado la subveccion, esperemos que nos den todo lo pedido. Gracias a todos por las ideas.
