### ISSUE TITLE
Cadenas Spicy

### ISSUE THREAD

**Issue by DiegoGarciaX2** [asrob-uc3m/impresoras-asrob#99]
Hay que imprimir adaptadores para instalar las cadenas del eje x e y en Spicy caldito

**Comment by DiegoGarciaX2** [comment]
https://www.thingiverse.com/thing:1905344/remixes
https://www.thingiverse.com/thing:2043493
Estos adaptadores deberian de funcionar, habria que poner una pequeña expansion horizontal (sobre 1mm)

**Comment by Siotma** [comment]
No estoy de acuerdo, esos adaptadores no tienen agujero pasante, como necesitan las cadenetas que hemos comprado. Además, las piezas que has enlazado tienen el macho en la parte externa y la hembra en la interna, mientras que las cadenetas que tenemos van al revés.

Véase #66 para detalles sobre las cadenetas.

**Comment by Siotma** [comment]
Buenas candidatas serían las siguientes piezas:

- https://www.thingiverse.com/thing:3072331
- https://www.thingiverse.com/thing:3072340
- https://www.thingiverse.com/thing:2862157

Que comience el reto!

**Comment by Siotma** [comment]
Después de hacer pruebas en mi casa, he comprobado que el tercer enlace que pasé no es compatible con las cadenas que tenemos. En su lugar, he diseñado los equivalentes de 10x20 a patir de los modelos de 10x10:

[chain_20.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2523112/chain_20.zip)

El próximo día llevaré una unidad de cada.

**Comment by CinnabarCinnamon** [comment]
Buscando sujeciones para cadenas en Hija hemos encontrado piezas útiles para esta issue.
[E3DV6_Open_Chain_Long_Solo_V4.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842126/E3DV6_Open_Chain_Long_Solo_V4.zip)
[E3DV6_Chain_Stepper_Mount_V4.zip](https://github.com/asrob-uc3m/impresoras-asrob/files/2842127/E3DV6_Chain_Stepper_Mount_V4.zip)
